### ISSUE TITLE
Issue with class variables in delegate script

### ISSUE THREAD

**Issue by jonathangreen** [cantaloupe-project/cantaloupe#221]
Hello. 

Its very possible I'm doing something silly since I'm not a ruby guy, but I'm trying to update to Cantaloupe 4 so I'm rewriting our delegates script and I'm trying to use a class variable in delegates.rb to share a mysql connection pool to do our authentication. This appears to cause issues in jruby. I know there are some thread safety issues using a class variables, but I'm being careful to avoid them.

I'm using:
```properties
source.static = HttpSource
HttpSource.lookup_strategy = ScriptLookupStrategy
```

It appears that defining any class variable causes jruby to choke.

I've reduced the test case to this:
```ruby
require 'java'

class CustomDelegate

  attr_accessor :context
  
  # this line causes all my problems
  @@shared_context = 12

  ##
  # @param options [Hash] Empty hash.
  # @return [String,Hash<String,String>,nil] String URI; Hash with `uri` key,
  #         and optionally `username` and `secret` keys; or nil if not found.
  #
  def httpsource_resource_info(options = {})
    logger = Java::edu.illinois.library.cantaloupe.script.Logger
    logger.debug('Entering httpsource_resource_info')
    return { 'uri' => "http://localhost:8080/objects/test:object/datastreams/JP2/content" }
  end

  def redirect(options = {})
  end

  def authorized?(options = {})
    true
  end

  def extra_iiif2_information_response_keys(options = {})
    {}
  end

  def source(options = {})
  end

  def azurestoragesource_blob_key(options = {})
  end

  def filesystemsource_pathname(options = {})
  end

  def jdbcsource_database_identifier(options = {})
  end

  def jdbcsource_media_type(options = {})
  end

  def jdbcsource_lookup_sql(options = {})
  end

  def s3source_object_info(options = {})
  end

  def overlay(options = {})
  end

  def redactions(options = {})
    []
  end

end
```

If I remove the `@@shared_context = 12` then everything works as expected. Doesn't matter what its called any shared context seems to cause this issue. 

Java stack trace: 
```
2018-06-14 16:06:38,640 DEBUG [qtp834133664-13] e.i.l.c.r.AbstractResource [AbstractResource.java:421] Identifier requested: dev%3Atest:object:JP2 -> decoded: dev:test:object:JP2 -> slashes substituted: dev:test:object:JP2
2018-06-14 16:06:38,642 INFO [qtp834133664-13] e.i.l.c.r.AbstractResource [AbstractResource.java:232] doInit(): handling GET http://xxx/iiif/2/dev%3Atest:object:JP2/info.json [Cookie: has_js=1; DrupalModuleFilter=activeTab%3Dall; Drupal.tableDrag.showWeight=0; SSESS98f5325fbba9b12d0be41957eb508a55=kCzUBmRXu78-453ysYYe7TOeAhg8Op9Xcp0j3jleQO8; Drupal.visitor.login_history=3856f333472881e015d02535cae12b7a8c7420b02c2fd317e962c747cf23fc12-b919665afb94aa0e0f1b3d1dfb1a1c5cebb714f5b1fd2fa559da941b1e78faec-9; Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8; User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15; X-Forwarded-Proto: HTTPS; X-Forwarded-Host: xxx; Connection: close; Host: xxx; Accept-Encoding: br, gzip, deflate; X-Forwarded-Port: 443; X-IIIF-ID: lyrasis:3690:JP2; X-Forwarded-Path: /; X-Forwarded-For: xxx; Accept-Language: en-ca; X-Forwarded-Server: xxx]
2018-06-14 16:06:38,660 DEBUG [qtp834133664-13] e.i.l.c.r.AbstractResource [AbstractResource.java:421] Identifier requested: dev%3Atest:object:JP2 -> decoded: dev:test:object:JP2 -> slashes substituted: dev:test:object:JP2
2018-06-14 16:06:38,662 INFO [qtp834133664-13] e.i.l.c.c.InfoCache [InfoCache.java:43] Max InfoCache capacity: 310728 (10% max heap / 150-byte expected average info size)
2018-06-14 16:06:38,672 DEBUG [qtp834133664-13] e.i.l.c.s.DelegateProxy [DelegateProxy.java:372] invokeUncached(): invoking context= with args: ({identifier=dev:test:object:JP2, request_headers={Cookie=has_js=1; DrupalModuleFilter=activeTab%3Dall; Drupal.tableDrag.showWeight=0; SSESS98f5325fbba9b12d0be41957eb508a55=kCzUBmRXu78-453ysYYe7TOeAhg8Op9Xcp0j3jleQO8; Drupal.visitor.login_history=3856f333472881e015d02535cae12b7a8c7420b02c2fd317e962c747cf23fc12-b919665afb94aa0e0f1b3d1dfb1a1c5cebb714f5b1fd2fa559da941b1e78faec-9, Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15, X-Forwarded-Proto=HTTPS, X-Forwarded-Host=dev-islandora.lyrasistechnology.org, Connection=close, Host=xxx, Accept-Encoding=br, gzip, deflate, X-Forwarded-Port=443, X-IIIF-ID=test:object:JP2, X-Forwarded-Path=/, X-Forwarded-For=xxx, Accept-Language=en-ca, X-Forwarded-Server=xxx}, client_ip=xxx, request_uri=http://xxx/iiif/2/dev%3Atest:object:JP2/info.json, cookies={has_js=1, DrupalModuleFilter=activeTab%3Dall, Drupal.tableDrag.showWeight=0, SSESS98f5325fbba9b12d0be41957eb508a55=kCzUBmRXu78-453ysYYe7TOeAhg8Op9Xcp0j3jleQO8, Drupal.visitor.login_history=3856f333472881e015d02535cae12b7a8c7420b02c2fd317e962c747cf23fc12-b919665afb94aa0e0f1b3d1dfb1a1c5cebb714f5b1fd2fa559da941b1e78faec-9}})
2018-06-14 16:06:38,680 ERROR [qtp834133664-13] o.r.C.RestletApplication [Slf4jLogger.java:230] Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
	at org.restlet.resource.ServerResource.get(ServerResource.java:723)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:662)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1020)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:856)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.jruby.embed.jsr223.JRubyEngine.invokeMethod(JRubyEngine.java:217)
	at edu.illinois.library.cantaloupe.script.DelegateProxy.invokeUncached(DelegateProxy.java:377)
	at edu.illinois.library.cantaloupe.script.DelegateProxy.setRequestContext(DelegateProxy.java:165)
	at edu.illinois.library.cantaloupe.script.DelegateProxy.instantiateDelegate(DelegateProxy.java:147)
	at edu.illinois.library.cantaloupe.script.DelegateProxy.<init>(DelegateProxy.java:138)
	at edu.illinois.library.cantaloupe.script.DelegateProxyService.newDelegateProxy(DelegateProxyService.java:137)
	at edu.illinois.library.cantaloupe.resource.AbstractResource.getDelegateProxy(AbstractResource.java:395)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGet(InformationResource.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
	... 64 common frames omitted
```

Feel free to just let me know I shouldn't be using class variables haha, I just thought it was weird.

**Comment by jonathangreen** [comment]
On a related note, do you use the delegate script to do auth lookups in mysql, and if so, do you use a connection pool to do the queries?

**Comment by adolski** [comment]
That's weird alright. I'm trying to set up an SSCCE using the same Ruby script that fails in Cantaloupe, but I can't get it to happen there.

Removing the line below seems to remedy this and is probably safe to do, but I'd like to look into it some more first:

https://github.com/medusa-project/cantaloupe/blob/0368a9763a323c139d312d75cb85b3bf53987ef2/src/main/java/edu/illinois/library/cantaloupe/script/DelegateProxy.java#L90

As a workaround, maybe you could use a constant, a class instance variable, or a global variable (`$shared_context`) instead.

----

I should add some info about connection pooling to the manual. If you are using JDBC via the JRuby-Java bridge, you could use the [HikariCP](https://github.com/brettwooldridge/HikariCP) pool, which is packaged in and used by JdbcSource and JdbcCache. It would work something like:

```ruby
# Class variables aren't working but you get the idea
@@dataSource = com.zaxxer.hikari.HikariDataSource.new
@@dataSource.setJdbcUrl 'mysql://...'
@@dataSource.setUsername 'user'
@@dataSource.setPassword 'password'
# other settings documented on github page

def httpsource_resource_info(options = {})
  conn = @@dataSource.getConnection # this is a java.sql.Connection
  begin
    # ...
  ensure
    conn.close # give it back to the pool
  end
end
```

^^^ Untested but see JdbcSource & JdbcCache for working examples. Note that HikariCP isn't part of the delegate script contract and it could go away etc. although that seems unlikely anytime soon.

**Comment by jonathangreen** [comment]
I got this working with a global variable and `HikariDataSource` as my connection pool, so its still kind of a weird one, but not as big a deal for me anymore.

**Comment by patdunlavey** [comment]
@jonathangreen can you post the code detailing your solution?

**Comment by jonathangreen** [comment]
Sure. This is the solution I am using: 
https://gist.github.com/jonathangreen/ee947eeacc9f9fd30ab0120a6fb40592

**Comment by patdunlavey** [comment]
Thank you very much!!!
