### ISSUE TITLE
Cantaloupe throws an exception for certain JPG documents

### ISSUE THREAD

**Issue by telliers** [cantaloupe-project/cantaloupe#284]
Hi,

We have a provider that sends us new publications every day from different publishers. They also generates JPG for the front covers and back covers of the books.

We get all those "packages" in the process and eventually displays the items in our website. We are using Cantaloupe for displaying JPG, with OpenSeaDragon.

Now, I recently discovered that the most recent front and back covers in JPG format, doesn't seem to be processed correctly by Cantaloupe and it generates an exception.

Here are the details with a JPG example.

URL called (Cantaloupe server) : http://img.banq.qc.ca/iiif/2/7STrZtu9lWs0lQaEWu4JkQ/full/225,/0/default.png

URL should return a small image, for a thumbnail.
The ID used is encrypted, and the first step that we do in Cantaloupe is to get infos about the image from our diffusion repository, as it can be seen in the logs (the part that calls the vpldsb.bnquebec.ca service).

Here's the log for that call : 
```
11:42:18.127 [http-nio-8080-exec-9] INFO  e.i.l.c.r.AbstractResource - doInit(): handling GET http://img.banq.qc.ca/iiif/2/7STrZtu9lWs0lQaEWu4JkQ/full/225,/0/default.png
11:42:18.127 [http-nio-8080-exec-9] DEBUG e.i.l.c.r.AbstractResource - Identifier requested: 7STrZtu9lWs0lQaEWu4JkQ -> decoded: 7STrZtu9lWs0lQaEWu4JkQ -> slashes substituted: 7STrZtu9lWs0lQaEWu4JkQ
11:42:18.127 [http-nio-8080-exec-9] INFO  e.i.l.c.c.FilesystemCache - getImageInfo(): hit: /var/cantaloupe/cache/info/a0/5f/b6/a05fb6561346b8e875160980914a7895.json
11:42:18.128 [http-nio-8080-exec-9] DEBUG e.i.l.c.c.InfoService - getInfo(): retrieved info of 7STrZtu9lWs0lQaEWu4JkQ from FilesystemCache in 1 msec
11:42:18.128 [http-nio-8080-exec-9] DEBUG e.i.l.c.c.InfoService - putInObjectCache(): ObjectCache is disabled; doing nothing
11:42:18.128 [http-nio-8080-exec-9] DEBUG e.i.l.c.o.OperationList - applyNonEndpointMutations(): redactions are disabled; skipping.
11:42:18.128 [http-nio-8080-exec-9] DEBUG e.i.l.c.o.OperationList - applyNonEndpointMutations(): overlays are disabled; skipping.
11:42:18.141 [http-nio-8080-exec-9] DEBUG e.i.l.c.s.RubyScriptEngine - invoke(Cantaloupe::FilesystemResolver::get_pathname): exec time: 13 msec
11:42:18.141 [http-nio-8080-exec-9] INFO  e.i.l.c.r.FilesystemResolver - Resolved 7STrZtu9lWs0lQaEWu4JkQ to /assetstore/63/68/05/63680513967642480534549518297682357999
11:42:18.142 [http-nio-8080-exec-9] INFO  e.i.l.c.p.ProcessorConnector - FileResolver -> FileProcessor connection between FilesystemResolver and JaiProcessor
11:42:18.142 [http-nio-8080-exec-9] INFO  e.i.l.c.c.FilesystemCache - getImageInfo(): hit: /var/cantaloupe/cache/info/a0/5f/b6/a05fb6561346b8e875160980914a7895.json
11:42:18.142 [http-nio-8080-exec-9] DEBUG e.i.l.c.c.InfoService - getInfo(): retrieved info of 7STrZtu9lWs0lQaEWu4JkQ from FilesystemCache in 0 msec
11:42:18.142 [http-nio-8080-exec-9] DEBUG e.i.l.c.c.InfoService - putInObjectCache(): ObjectCache is disabled; doing nothing
DELEGATE : Executing self.authorized delegate
Get access (restrictions) info from service : service_base_uri=http://vpldsb.bnquebec.ca/get-bitstream-path
identifier :7STrZtu9lWs0lQaEWu4JkQ
client_ip :10.9.1.108
client_ip_from_headers :10.9.1.108
request uri: http://vpldsb.bnquebec.ca/get-bitstream-path?ebsid=7STrZtu9lWs0lQaEWu4JkQ&ip=10.9.1.108
Get access (restrictions) info from service : service_base_uri=http://vpldsb.bnquebec.ca/get-bitstream-path
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <bitstream>
        <id>14121765</id>
        <eid>7STrZtu9lWs0lQaEWu4JkQ</eid>
        <access>true</access>
        <path>/assetstore/63/68/05/63680513967642480534549518297682357999</path>
        <mime>image/jpeg</mime>
        <size>1751879</size>
        <url>http://collections.banq.qc.ca/retrieve/14121765</url>
        <name>9782896621668.jpg</name>
    </bitstream>
</root>
accessResponse: true
11:42:18.190 [http-nio-8080-exec-9] DEBUG e.i.l.c.s.RubyScriptEngine - invoke(Cantaloupe::authorized?): exec time: 48 msec
11:42:18.190 [http-nio-8080-exec-9] DEBUG e.i.l.c.r.AbstractResource - Public identifier requested: 7STrZtu9lWs0lQaEWu4JkQ | X-IIIF-ID header: null
11:42:18.190 [http-nio-8080-exec-9] DEBUG e.i.l.c.r.AbstractResource - X-Forwarded headers: Proto: HTTP; Host: img.banq.qc.ca; Port: 80; Path:
11:42:18.190 [http-nio-8080-exec-9] DEBUG e.i.l.c.r.AbstractResource - Base URI assembled: http://img.banq.qc.ca
11:42:18.190 [http-nio-8080-exec-9] INFO  e.i.l.c.c.FilesystemCache - newOutputStream(): miss; caching 7STrZtu9lWs0lQaEWu4JkQ_scale:225,,bicubic_encode:png_UNDEFINED_8.png
11:42:18.191 [http-nio-8080-exec-9] DEBUG e.i.l.c.r.ImageRepresentation - Writing to the response & derivative cache simultaneously
11:42:18.191 [http-nio-8080-exec-9] DEBUG e.i.l.c.p.i.JPEGImageReader - ImageIO plugin preferences: com.sun.imageio.plugins.jpeg.JPEGImageReader
11:42:18.191 [http-nio-8080-exec-9] DEBUG e.i.l.c.p.i.JPEGImageReader - Using com.sun.imageio.plugins.jpeg.JPEGImageReader
11:42:18.191 [http-nio-8080-exec-9] DEBUG e.i.l.c.p.i.JPEGImageReader - Ignoring metadata? true
11:42:18.285 [http-nio-8080-exec-9] DEBUG e.i.l.c.p.JAIUtil - scaleImageUsingSubsampleAverage(): width: 16.071428571428573%; height: 16.072255673923113%
11:42:18.285 [http-nio-8080-exec-9] DEBUG e.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream - close(): closing stream for 7STrZtu9lWs0lQaEWu4JkQ_scale:225,,bicubic_encode:png_UNDEFINED_8.png
11:42:18.285 [http-nio-8080-exec-9] DEBUG e.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream - close(): deleting zero-byte file: /var/cantaloupe/cache/image/a0/5f/b6/a05fb6561346b8e875160980914a7895_8648e53bdd36c61d5692dba99fddb020.png_http-nio-8080-exec-9.tmp
11:42:18.286 [http-nio-8080-exec-9] DEBUG e.i.l.c.r.ImageRepresentation - write(): JFIF APP0 must be first marker after SOI
11:42:18.286 [http-nio-8080-exec-9] INFO  e.i.l.c.c.FilesystemCache - purge(OperationList): purging 7STrZtu9lWs0lQaEWu4JkQ_scale:225,,bicubic_encode:png_UNDEFINED_8.png...
11:42:18.286 [http-nio-8080-exec-9] ERROR o.r.C.Server - An exception occurred writing the response entity
java.lang.NullPointerException: null
        at edu.illinois.library.cantaloupe.processor.imageio.AbstractImageReader.readRendered(AbstractImageReader.java:527)
        at edu.illinois.library.cantaloupe.processor.imageio.ImageReader.readRendered(ImageReader.java:257)
        at edu.illinois.library.cantaloupe.processor.JaiProcessor.process(JaiProcessor.java:141)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:175)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:130)
        at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
        at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
        at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
        at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:191)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
11:42:18.287 [http-nio-8080-exec-9] WARN  o.r.C.Server - Error while handling an HTTP server call
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
        at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:457)
        at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:388)
        at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:208)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

I attached the original JPG file used in the example above, to the issue.

Is it something that can be related to the nature of this JPG or the way it was generated? For example, Cantaloupe doesn't have any problem with the back cover of the same book related to the issue explained above.

Thanks.
![14121765](https://user-images.githubusercontent.com/18740213/57237111-807eae80-6ff4-11e9-9239-e55db24cb62e.jpg)

**Comment by adolski** [comment]
Hi @telliers,

Thanks for reporting this. It seems that the error message ("JFIF APP0 must be first marker after SOI") is wrong, because the image does contain an APP0 marker immediately after the SOI marker. I don't know why this image is causing problems and not the other one, but since the error is coming from inside Image I/O, I probably wouldn't be able to fix it even if I did know.

So instead, I pushed a workaround to the `release/3.4` branch, and also merged it into the newer branches. This enables the request to succeed, but without metadata copying.

I don't know about doing new releases for these older versions, but you are welcome to build yourself a snapshot. Another option might be to switch to Java2dProcessor which doesn't appear to be affected.

**Comment by telliers** [comment]
You mean by modifying one of the two following lines in the properties file  : 

```
processor.jp2 = ImageMagickProcessor
processor.jpg = JaiProcessor
```

Which one is used in my case?

**Comment by adolski** [comment]
To assign Java2dProcessor to read JPEGs, you'd set `processor.jpg = Java2dProcessor`

**Comment by telliers** [comment]
OK thanks. We'll try that and see if we have better results with that processor.
