### ISSUE TITLE
Can't load libturbojpeg.so

### ISSUE THREAD

**Issue by mmatela** [cantaloupe-project/cantaloupe#287]
With cantaloupe 4.1.1 I get errors when trying to open a jpeg file. On the first try:

    java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at edu.illinois.library.cantaloupe.processor.ProcessorFactory.newProcessor(ProcessorFactory.java:75)
    	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGET(InformationResource.java:134)
    	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:96)
    	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:34)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    	[...]
    Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /opt/libjpeg-turbo/lib/libturbojpeg.so
    	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
    	at java.lang.Runtime.load0(Runtime.java:809)
    	at java.lang.System.load(System.java:1086)
    	at org.libjpegturbo.turbojpeg.TJLoader.load(TJLoader.java:46)
    	at org.libjpegturbo.turbojpeg.TJ.&#60;clinit&#62;(TJ.java:571)
    	at edu.illinois.library.cantaloupe.processor.codec.turbojpeg.TurboJPEGImageReader.&#60;clinit&#62;(TurboJPEGImageReader.java:61)
    	at edu.illinois.library.cantaloupe.processor.TurboJpegProcessor.&#60;init&#62;(TurboJpegProcessor.java:104)
    	... 35 more

On consecutive tries:

    java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at edu.illinois.library.cantaloupe.processor.ProcessorFactory.newProcessor(ProcessorFactory.java:75)
    	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGET(InformationResource.java:134)
    	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:96)
    	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:34)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    	[...]
    Caused by: java.lang.NoClassDefFoundError: Could not initialize class edu.illinois.library.cantaloupe.processor.codec.turbojpeg.TurboJPEGImageReader
    	at edu.illinois.library.cantaloupe.processor.TurboJpegProcessor.&#60;init&#62;(TurboJpegProcessor.java:104)
    	... 40 more

I managed to work around this by setting `processor.selection_strategy = ManualSelectionStrategy`.
But I don't think it should be necessary, `AutomaticSelectionStrategy` should recognize when turbojpeg is not available and fall back to 'Java2dProcessor' or something.

As a side note, do you have any advice on how to enable turbojpeg on Centos 7? The `/opt/` folder is empty. I've installed packets I found in yum: libjpeg-turbo.i686, libjpeg-turbo.x86_64, turbojpeg.i686, turbojpeg.x86_64, but that didn't help.

**Comment by adolski** [comment]
Thanks for reporting this, @mmatela. I agree that it should work the way you described and the above commit fixes it.

For libjpeg-turbo, I assume that the yum version is compiled without Java support, so you may need to build it from source. See here: https://cantaloupe-project.github.io/manual/4.1/processors.html#TurboJpegProcessor
