### ISSUE TITLE
Configured JaiProcessor, still using ImageIO?

### ISSUE THREAD

**Issue by mmatela** [cantaloupe-project/cantaloupe#327]
My original problem is that I have an image that is apparently inconsistent and I see an exception like this:

    javax.imageio.IIOException: Invalid icc profile: inconsistent num_markers fields
    	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
    	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:609)
    	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:347)
    	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getNumImagesOnThread(JPEGImageReader.java:411)
    	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getNumImages(JPEGImageReader.java:389)
    	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.getNumImages(AbstractIIOImageReader.java:151)
    	at edu.illinois.library.cantaloupe.processor.AbstractImageIOProcessor.readInfo(AbstractImageIOProcessor.java:82)
    	at edu.illinois.library.cantaloupe.cache.InfoService.readInfo(InfoService.java:198)
    	at edu.illinois.library.cantaloupe.cache.InfoService.getOrReadInfo(InfoService.java:134)
    	at edu.illinois.library.cantaloupe.cache.CacheFacade.getOrReadInfo(CacheFacade.java:67)
    	at edu.illinois.library.cantaloupe.resource.PublicResource.getOrReadInfo(PublicResource.java:110)
    	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGET(InformationResource.java:139)

The image can be displayed in many other viewers without problems, so I was hoping I can switch to another processor as a workaround. But I still see the same exception. Here are debug logs:

    INFO  e.i.l.c.r.i.v.InformationResource - Handling GET /cantaloupe/[...]/info.json
    DEBUG e.i.l.c.r.i.v.InformationResource - Request headers: [...]
    DEBUG e.i.l.c.i.Identifier - Raw path component: [...]
    DEBUG e.i.l.c.s.FilesystemSource - Resolved [...]
    DEBUG e.i.l.c.p.ProcessorFactory - JaiProcessor selected for format JPG (ManualSelectionStrategy offered JaiProcessor, Java2dProcessor)
    DEBUG e.i.l.c.p.ProcessorConnector - FileSource -> FileProcessor connection between FilesystemSource and JaiProcessor
    DEBUG e.i.l.c.p.c.JPEGImageReader - Using com.sun.imageio.plugins.jpeg.JPEGImageReader
    DEBUG e.i.l.c.p.c.JPEGImageReader - Ignoring metadata? true
    INFO  e.i.l.c.r.ErrorResource - Handling GET /cantaloupe/[...]/info.json
    DEBUG e.i.l.c.r.ErrorResource - Request headers: [..]
    DEBUG e.i.l.c.r.ErrorResource - Base URI assembled from X-Forwarded headers: [...]
    DEBUG e.i.l.c.r.HandlerServlet - Responded to GET /[...]/info.json with HTTP 500 in 23 msec

I'm guessing the problem is that getting image metadata still uses ImageIO?
Is there a way around this?
Or maybe you could change the logic to ignore errors like that and just return some empty or guessed data (like getNumImages can safely assume 1, right)?

**Comment by adolski** [comment]
This is a fault of the Sun/Oracle Image I/O JPEG plugin. It's very strict. Unfortunately there is no workaround that I know of as all of the reading methods (not only `getNumImages()`) will throw the same exception.

The recommended workaround for now is to use TurboJpegProcessor instead. This is much more compatible and also faster. [The manual](https://cantaloupe-project.github.io/manual/4.1/processors.html#TurboJpegProcessor) contains instructions for getting it working.

**Comment by mmatela** [comment]
OK, thanks for the information.
