### ISSUE TITLE
Image failed to load when retrieving from S3 Source

### ISSUE THREAD

**Issue by white-ws** [cantaloupe-project/cantaloupe#364]
#### Cantaloupe version

4.1.5

#### Description

Images with size > 2.2GB failed to load 

#### Steps to reproduce

1.  Upload a large image (>2.2 GB) `large-img.tiff` to S3 bucket `my-bucket`
2. Call GET `iiif/2/large-img.tiff/info.json`

#### Expected behaviour

Response contains `info.json`

#### Actual behaviour

500 Internal Server Error: Couldn't seek!

#### Configuration

```
#----------------------------------------
# S3Source
#----------------------------------------

S3Source.endpoint = s3.ap-northeast-1.amazonaws.com

S3Source.access_key_id =
S3Source.secret_key =

S3Source.lookup_strategy = BasicLookupStrategy

S3Source.BasicLookupStrategy.bucket.name = my-bucket
S3Source.BasicLookupStrategy.path_prefix =
S3Source.BasicLookupStrategy.path_suffix =

S3Source.chunking.enabled = true
S3Source.chunking.chunk_size = 512K
S3Source.chunking.cache.enabled = true
S3Source.chunking.cache.max_size = 5M
```

#### Log from cantaloupe

```
Requesting bytes 0-1048575 from my-bucket/large-img.tiff
Requesting bytes 1780482048-1781530623 from my-bucket/large-img.tiff
Requesting bytes -1995440128--1994391553 from my-bucket/large-img.tiff

java.io.IOException: my-bucket/large-img.tiff
	at edu.illinois.library.cantaloupe.source.S3Source.newObjectInputStream(S3Source.java:194)
	at edu.illinois.library.cantaloupe.source.S3HTTPImageInputStreamClient.sendGETRequest(S3HTTPImageInputStreamClient.java:71)
	at edu.illinois.library.cantaloupe.source.stream.HTTPImageInputStream.downloadChunk(HTTPImageInputStream.java:341)
	at edu.illinois.library.cantaloupe.source.stream.HTTPImageInputStream.fetchChunk(HTTPImageInputStream.java:329)
	at edu.illinois.library.cantaloupe.source.stream.HTTPImageInputStream.prepareWindowBuffer(HTTPImageInputStream.java:310)
	at edu.illinois.library.cantaloupe.source.stream.HTTPImageInputStream.readIncrement(HTTPImageInputStream.java:276)
	at edu.illinois.library.cantaloupe.source.stream.HTTPImageInputStream.read(HTTPImageInputStream.java:255)
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readShort(ImageInputStreamImpl.java:228)
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readUnsignedShort(ImageInputStreamImpl.java:242)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.locateImage(TIFFImageReader.java:657)
	... 46 more
Caused by: io.minio.errors.InvalidArgumentException: offset should be zero or greater
	at io.minio.MinioClient.getObject(MinioClient.java:1642)
	at edu.illinois.library.cantaloupe.source.S3Source.newObjectInputStream(S3Source.java:183)
	... 55 more
```

**Comment by adolski** [comment]
Hi @white-ws,

I believe I found the root problem of this (in `getRange()`), and I decided to fix that, instead of using #365. But thanks for reporting this and submitting the PR!
