### ISSUE TITLE
cantaloupe-4.1.6, No Suitable driver, Windows 10

### ISSUE THREAD

**Issue by apiszcz** [cantaloupe-project/cantaloupe#385]
I am having a configuration issue where cantaloupe/java is not finding the postgressql jdbc driver which I downloaded from here:
https://jdbc.postgresql.org/download.html

I placed the postgresql-42.2.14.jar in the same folder as the .war file and in the same folder as the cantaloupe startup bat file.

```
SET CLASSPATH=C:\test\postgresjdbc\postgresql-42.2.14.jar

java ^
-Dcantaloupe.config=C:/test/_cantaloupe/cantaloupe.properties ^
-Xmx2g ^
-jar C:/test/cantaloupe/cantaloupe-4.1.6.war
```

```
500 Internal Server Error
Failed to get driver instance for jdbcUrl=jdbc:postgresql://localhost:5432/img

Caused by: java.sql.SQLException: No suitable driver
	at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298)
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:103)
```

**Comment by apiszcz** [comment]
create, tested a separate java JDBC access program and it connects to the database without error.

```
import java.sql.Connection;
import java.sql.DriverManager;

public class PostgreSQLJDBC {
   public static void main(String args[]) {
      Connection c = null;
      try {
         Class.forName("org.postgresql.Driver");
         c = DriverManager
            .getConnection("jdbc:postgresql://localhost:5500/data",
            "postgres", "");
      } catch (Exception e) {
         e.printStackTrace();
         System.err.println(e.getClass().getName()+": "+e.getMessage());
         System.exit(0);
      }
      System.out.println("Opened database successfully");
   }
}
```

java -cp .;postgresql-42.2.14.jar PostgreSQLJDBC
Opened database successfully

**Comment by adolski** [comment]
For 4.1.x, the JDBC JAR would need to be in one of the Java extension directories (`System.getProperty("java.ext.dirs")`). The extension dirs mechanism was removed in Java 9, so you'd have to use 8.

On the `develop` branch I believe the ability to load classes from other JARs is currently broken. That's because `-cp` invocation isn't possible, `-jar` invocation overrides all other classpath configuration, and the minimum Java version is 11, which doesn't support extension dirs. To fix this, the application is probably going to get repackaged in a way that will support -cp invocation (#339).

**Comment by apiszcz** [comment]
Thank you, i am sure I would not have figured this out.
C:\test\lw\java8\jre\lib\ext;C:\windows\Sun\Java\lib\ext
Placed the JDBC jar if the first choice above and I am making it farther along the path.
10:46:05.057 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@420348d2

I am not sure my UUID is a good id though
scale constraint stripped:

Thank you.

**Comment by apiszcz** [comment]
With the database connection apparently active, I have the following configuration in delegates.rb
I tried identifier and detuuid in the jdbcsource_database_identifier.

```
  def jdbcsource_database_identifier(options = {})
    context['identifier']
  end
  
  def jdbcsource_media_type(options = {})
  end

  def jdbcsource_lookup_sql(options = {})
        'SELECT imagebytea'
        'FROM testschema.datatable'
        'WHERE detuuid = ?'
  end
```
QUERY URL : 
http://localhost:8182/iiif/2/551ff84a-9e47-44ff-9e69-01fcb8c40826/0,0,200,200/full/0/default.jpg

from the web browser:
java.io.IOException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "WHERE"
  Position: 1

Java console message
Responded to GET /iiif/2/551ff84a-9e47-44ff-9e69-01fcb8c40826/0,0,200,200/full/0/default.jpg with HTTP 500 in 588 msec

**Comment by adolski** [comment]
Try:

```ruby
  def jdbcsource_lookup_sql(options = {})
        'SELECT imagebytea ' +
        'FROM testschema.datatable ' +
        'WHERE detuuid = ?'
  end
```

**Comment by apiszcz** [comment]
MUCH better , full string, needed, got it. Latest error
The data is stored as bytea in postgres.

500 Internal Server Error
org.libjpegturbo.turbojpeg.TJDecompressor.decompress([BI[IIIIIIII)V

**Comment by adolski** [comment]
It looks like `TJDecompressor.decompress()` is not liking the image data it's receiving from JdbcSource. Are you sure it's valid JPEG image data? Can you dump it to a file and open it in typical JPEG reader software? If it's not JPEG then you'll probably have to modify your `jdbcsource_media_type()` method to tell the image server what it is.

I just tried reading a JPEG image out of a bytea column and wasn't able to reproduce this error (Cantaloupe 4.1.6, Postgres 12.1, same JDBC JAR version).

**Comment by apiszcz** [comment]
It is a JPEG, JFIF in header, views in DBeaver value field as image. I can save to file and view as image. I'm guessing it is my query response, it takes 5 to 8 seconds then seems to timeout.

```
10:26:28.456 [qtp2096057945-21] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@56cfa455                                                                                                          
10:26:28.458 [qtp2096057945-21] INFO  c.z.h.HikariDataSource - JdbcSourcePool - Start completed.                                                                                                                                                
10:26:28.464 [qtp2096057945-21] INFO  e.i.l.c.s.JdbcSource - Using PostgreSQL JDBC Driver 42.2.14                                                                                                                                               
10:26:28.467 [qtp2096057945-21] INFO  e.i.l.c.s.JdbcSource - Connection string: jdbc:postgresql://testdatabase:5500/img                                                                                                                        
10:26:28.474 [qtp2096057945-21] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): jdbcsource_lookup_sql() returned SELECT objimgdata FROM imgdatatable WHERE uuid = ? for args: (none) in 0 msec                                
10:26:28.479 [qtp2096057945-21] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): jdbcsource_database_identifier() returned c35e2ec7-d82a-4ac9-818a-0f5f57ad9487 for args: (none) in 1 msec                                                     
10:26:28.480 [qtp2096057945-21] DEBUG e.i.l.c.s.JdbcSource - SELECT objimgdata FROM imgdatatable WHERE uuid = ?                                                                                                                 
10:26:28.561 [JdbcSourcePool housekeeper] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Pool stats (total=1, active=1, idle=0, waiting=0)                                                                                                         
10:26:28.949 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@63cad743                                                                                           
10:26:29.582 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@6d0d254a                                                                                           
10:26:30.126 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@6932bc33                                                                                           
10:26:30.882 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@2c302f71                                                                                           
10:26:31.570 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@1975857b                                                                                           
10:26:32.201 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@1dd6c46a                                                                                           
10:26:33.010 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@617930c7                                                                                           
10:26:33.903 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@4c1fd03e                                                                                           
10:26:34.473 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@7974da9b                                                                                           
10:26:34.944 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@522ab44b                                                                                           
10:26:35.297 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@7a7d59c1                                                                                           
10:26:35.724 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@4851e890                                                                                           
10:26:36.495 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@172e5303                                                                                           
10:26:39.990 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@10213541                                                                                           
10:26:42.868 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@2c5d5                                                                                              
10:26:43.417 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@4750b82d                                                                                           
10:26:45.765 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@22834d8f                                                                                           
10:26:46.571 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@3b91ffa3                                                                                           
10:26:48.387 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@2daba969                                                                                           
10:26:49.640 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@6ff8fd21                                                                                           
10:26:50.062 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@572f2a64                                                                                           
10:26:50.382 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@6377abc5                                                                                           
10:26:50.698 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@1367a623                                                                                           
10:26:51.018 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@3bde509b                                                                                           
10:26:51.302 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@158c218e                                                                                           
10:26:51.637 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@4b7b8979                                                                                           
10:26:51.941 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@6583788b                                                                                           
10:26:52.321 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@2c10a628                                                                                           
10:26:52.760 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@58e46275                                                                                           
10:26:53.576 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@4fc30851                                                                                           
10:26:54.187 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@31fa7602                                                                                           
10:26:55.445 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Added connection org.postgresql.jdbc.PgConnection@18f2a7f3                                                                                           
10:26:55.447 [JdbcSourcePool connection adder] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - After adding stats (total=33, active=1, idle=32, waiting=0)                                                                                          
10:26:56.581 [qtp2096057945-21] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): jdbcsource_media_type() returned null for args: (none) in 0 msec                                                                                              
10:26:56.617 [qtp2096057945-21] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): jdbcsource_lookup_sql() returned SELECT objimgdata FROM imgdatatable WHERE uuid = ? for args: (none) in 0 msec                                
10:26:56.619 [qtp2096057945-21] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): jdbcsource_database_identifier() returned c35e2ec7-d82a-4ac9-818a-0f5f57ad9487 for args: (none) in 0 msec                                                     
10:26:56.620 [qtp2096057945-21] DEBUG e.i.l.c.s.JdbcSource - SELECT objimgdata FROM imgdatatable WHERE uuid = ?                                                                                                                 
10:26:58.563 [JdbcSourcePool housekeeper] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Pool stats (total=33, active=1, idle=32, waiting=0)                                                                                                       
10:27:23.403 [qtp2096057945-21] DEBUG e.i.l.c.p.ProcessorFactory - TurboJpegProcessor selected for format JPG (AutomaticSelectionStrategy offered TurboJpegProcessor, Java2dProcessor, GraphicsMagickProcessor, ImageMagickProcessor)           
10:27:23.412 [qtp2096057945-21] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): jdbcsource_lookup_sql() returned SELECT objimgdata FROM imgdatatable WHERE uuid = ? for args: (none) in 1 msec                                
10:27:23.414 [qtp2096057945-21] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): jdbcsource_database_identifier() returned c35e2ec7-d82a-4ac9-818a-0f5f57ad9487 for args: (none) in 0 msec                                                     
10:27:23.416 [qtp2096057945-21] DEBUG e.i.l.c.p.ProcessorConnector - StreamSource -> StreamProcessor connection between JdbcSource and TurboJpegProcessor                                                                                       
10:27:23.452 [qtp2096057945-21] DEBUG e.i.l.c.s.JdbcSource - SELECT objimgdata FROM imgdatatable WHERE uuid = ?                                                                                                                 
10:27:28.387 [qtp2096057945-21] DEBUG e.i.l.c.c.InfoService - readInfo(): read c35e2ec7-d82a-4ac9-818a-0f5f57ad9487 from TurboJpegProcessor in 7 msec                                                                                           
10:27:28.392 [work-nm-7448414] DEBUG e.i.l.c.c.InfoService - putInObjectCache(): adding info: c35e2ec7-d82a-4ac9-818a-0f5f57ad9487 (new size: 1)                                                                                                
10:27:28.393 [work-nm-7448414] DEBUG e.i.l.c.c.InfoCache - putInObjectCache(): adding info: c35e2ec7-d82a-4ac9-818a-0f5f57ad9487 (new size: 1)                                                                                                  
10:27:28.408 [qtp2096057945-21] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): authorize() returned true for args: (none) in 0 msec                                                                                                          
10:27:28.415 [qtp2096057945-21] DEBUG e.i.l.c.r.i.v.ImageResource - Base URI assembled from X-Forwarded headers: http://localhost:8182                                                                                                          
10:27:28.420 [qtp2096057945-21] DEBUG e.i.l.c.r.ImageRepresentation - Derivative cache not available; writing directly to the response                                                                                                          
10:27:28.429 [qtp2096057945-21] INFO  e.i.l.c.r.ErrorResource - Handling GET /iiif/2/c35e2ec7-d82a-4ac9-818a-0f5f57ad9487/0,0,50,50/full/0/default.jpg                                                                                          
10:27:28.430 [qtp2096057945-21] DEBUG e.i.l.c.r.ErrorResource - Request headers: Cookie: username-localhost-8889="2|1:0|10:1592588083|23:username-localhost-8889|44:OWNmMWJjODZjNDViNGQ0ZmE4N2VmZWIxOTg1MDVhZTU=|e75edf7c52306b09fd7bf15dc954187
502717c41867ffeb718a3a6e037d891a0"; _xsrf=2|b3293968|13155860dd03b1786d8a3f44e17acfa5|1593425196; username-localhost-8890="2|1:0|10:1593463225|23:username-localhost-8890|44:MjJhNmQzMzYwMmM4NDE3ZmFjM2EzNGJmMjQ5Yzk2MmM=|1ac593e8aca7146584460e
68610d67796d09428afce1578ff127dd322cdc936f"; username-localhost-8888="2|1:0|10:1593522655|23:username-localhost-8888|44:MjBhOWNmMjg4M2E2NDVkZGJkYjlkZTE0OWFiMDFkMWU=|b4c21c8fb2c1686714c5d13744d9e96c42f7d1d3232693317e9636f471deb142"; Accept: 
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9; Upgrade-Insecure-Requests: 1; Connection: keep-alive; User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleW
ebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36; Sec-Fetch-Site: none; Sec-Fetch-Dest: document; Host: localhost:8182; DNT: 1; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.9; Sec-Fetch-Mode: navigate
                                                                                                                                                                                                                                                
10:27:28.432 [qtp2096057945-21] DEBUG e.i.l.c.r.ErrorResource - Base URI assembled from X-Forwarded headers: http://localhost:8182                                                                                                              
10:27:28.440 [qtp2096057945-21] DEBUG e.i.l.c.r.HandlerServlet - Responded to GET /iiif/2/c35e2ec7-d82a-4ac9-818a-0f5f57ad9487/0,0,50,50/full/0/default.jpg with HTTP 500 in 60817 msec                                                         
10:27:28.564 [JdbcSourcePool housekeeper] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Pool stats (total=33, active=0, idle=33, waiting=0)                                                                                                       
10:27:58.566 [JdbcSourcePool housekeeper] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Pool stats (total=33, active=0, idle=33, waiting=0)                                                                                                       
10:28:28.568 [JdbcSourcePool housekeeper] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Pool stats (total=33, active=0, idle=33, waiting=0)                                                                                                       
10:28:58.571 [JdbcSourcePool housekeeper] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Pool stats (total=33, active=0, idle=33, waiting=0)                                                                                                       
10:29:28.573 [JdbcSourcePool housekeeper] DEBUG c.z.h.p.HikariPool - JdbcSourcePool - Pool stats (total=33, active=0, idle=33, waiting=0)                                   
```

**Comment by apiszcz** [comment]
It works!
I used full/full/0/default.jpg
Thanks!
