### ISSUE TITLE
[4.1.x] Failure to parse `java.version` at runtime

### ISSUE THREAD

**Issue by MorrisonCole** [cantaloupe-project/cantaloupe#387]
*Steps to reproduce:*

* Run cantaloupe with an EA version of Java (I discovered this using the `openjdk:14-alpine` Docker image) 
* Request an image, see an exception like:

```
java.lang.NumberFormatException: For input string: &#34;14-ea&#34;
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at edu.illinois.library.cantaloupe.util.SystemUtils.parseJavaMajorVersion(SystemUtils.java:31)
	at edu.illinois.library.cantaloupe.util.SystemUtils.getJavaMajorVersion(SystemUtils.java:12)
	at edu.illinois.library.cantaloupe.processor.codec.TIFFImageReader.getApplicationPreferredIIOImplementations(TIFFImageReader.java:54)
	at 
```

Basically this is expecting a number separated with `.`, but some versions of Java have different formats, for example on my image:

```
$ java -XshowSettings:properties -version
java.version = 14-ea
```

It looks like Cantaloupe doesn't need to know anything other than if it's Java 9+, so I made a [quick change on our fork](https://github.com/medmain/cantaloupe/commit/1da3647a9a449155da3fdfc730ac9343208b6cec#diff-2bf69a58fc683325c2a0c5a5e80b8243R8) that simplifies this and avoids the bug. If you'd like a similar PR, I could tidy it up a bit and do that 😄

**Comment by adolski** [comment]
Thanks for reporting this, @MorrisonCole, it is fixed now.
