### ISSUE TITLE
Calls to Jetty and multi-domain certificates since 9.4.24

### ISSUE THREAD

**Issue by wrlewis** [cantaloupe-project/cantaloupe#395]
Cantaloupe 4.1.6 has Jetty 9.4.24 v. 20191120 embedded.  This is working very well for us in the http world.

However, as soon as we applied a multi-domain certificate, startup fails with the log segment below.

The maintainers of Jetty have been aware of this problem and calling on a variety of projects to adjust the code making the calls, specifically: SslContextFactory.Server instead of SslContextFactory 

==anonymized version of log ===

2020-08-11 12:31:19.502:INFO:oejus.SslContextFactory:main: x509=X509@5443d039(certificate_name,h=[1.example.com, 2.example.com, 3.example.com, 4.example.com, 5.example.com],w=[]) for SslContextFactory@2631f68c[provider=null,keyStore=file:///C:/Program%20Files/Java/jre1.8.0_251/lib/security/cacerts,trustStore=null]
Exception in thread "main" java.lang.UnsupportedOperationException: X509ExtendedKeyManager only supported on Server
	at org.eclipse.jetty.util.ssl.SslContextFactory.newSniX509ExtendedKeyManager(SslContextFactory.java:1273)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1255)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:374)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:92)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:320)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at edu.illinois.library.cantaloupe.ApplicationServer.start(ApplicationServer.java:350)
	at edu.illinois.library.cantaloupe.StandaloneEntry.main(StandaloneEntry.java:97)

**Comment by adolski** [comment]
Hi @wrlewis ,
> The maintainers of Jetty have been aware of this problem and calling on a variety of projects to adjust the code making the calls, specifically: SslContextFactory.Server instead of SslContextFactory

Can you post a link to this discussion?

**Comment by wrlewis** [comment]
Within Jetty: https://github.com/eclipse/jetty.project/issues/4425

In other projects, responding to this:
https://issues.apache.org/jira/browse/CALCITE-4095
https://github.com/spring-projects/spring-boot/issues/16827
https://www.symmetricds.org/issues/view.php?id=4408
https://github.com/opentable/otj-server/pull/113
https://issues.apache.org/jira/browse/SOLR-14105

and a search on ""X509ExtendedKeyManager only supported on Server" yields more

**Comment by adolski** [comment]
Thanks!
