### ISSUE TITLE
Server responds with Unsupported Image Type on Pyramidal TIFF from PNG RGBA

### ISSUE THREAD

**Issue by barryspearce** [cantaloupe-project/cantaloupe#397]
Whilst converting most images works, converting a PNG with RGBA seems to produce a TIFF that causes cantaloupe to respond with Unsupported Image Type.

The PNG is attached, it was converted to pyramid tiff using:

magick convert in.png -define tiff:tile-geometry=256x256 -compress jpeg ptif:outfilename

Gwenview on linux can view the resultant tiff files.

Neither debug out or the response provide the info I need to solve this. Is this an error in ImageMagick conversion or an issue with cantaloupe?
![a1](https://user-images.githubusercontent.com/18211861/90961183-fc796000-e49e-11ea-90ed-68d6b30b6c22.png)

500 Internal Server Error
Unsupported Image Type
java.io.IOException: Unsupported Image Type
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:148)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:76)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:213)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: edu.illinois.library.cantaloupe.processor.ProcessorException: Unsupported Image Type
	at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:70)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.process(ImageRepresentation.java:179)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:146)
	... 36 more
Caused by: javax.imageio.IIOException: Unsupported Image Type
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1139)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1110)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFJPEGDecompressor.decodeRaw(TIFFJPEGDecompressor.java:278)
	at it.geosolutions.imageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2627)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1708)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:2009)
	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.tileAwareRead(AbstractIIOImageReader.java:506)
	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.readSmallestUsableSubimage(AbstractIIOImageReader.java:446)
	at edu.illinois.library.cantaloupe.processor.codec.TIFFImageReader.read(TIFFImageReader.java:160)
	at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:64)
	... 38 more

**Comment by adolski** [comment]
Hi @barryspearce,

This error is coming from the JDK JPEG plugin used internally by Cantaloupe to decode JPEG-compressed TIFF tiles. This plugin is notoriously stringent and fails to read some valid JPEGs. I have an idea about how to fix this, but it will be a longer term project.

If you have a choice, a workaround would be to compress your TIFFs using any encoding other than JPEG, such as LZW.

**Comment by barryspearce** [comment]
I assume that encoding a TIFF with jpeg will reduce the processing required when delivering jpeg tiles compared to LZW? Or does it not matter?

re; VIPS - Brilliant. That solved the problem completely!

Closing as this appears to be a conversion issue rather than a Cantaloupe issue.
Thanks for you help!
