### ISSUE TITLE
Return source URL of an image when using HttpSource

### ISSUE THREAD

**Issue by arnikz** [cantaloupe-project/cantaloupe#398]
Hi,

I'm playing around with the Cantaloupe server (v4.6.1) and would like the source URLs of images - residing on a different (archive) server - to be included in the response (e.g.  using `dcterms:source` -> `https://myexamplearchive.org/images/...`). Could you please help?

My `cantaloupe.properties` config:

```
source.static = HttpSource
...
HttpSource.BasicLookupStrategy.url_prefix = https://myexamplearchive.org/images/
```

An example HTTP request/response:
```
$ curl -L http://localhost:8182/iiif/2/MMNAT01_AF_NNM001001033_001/info.json
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "http://localhost:8182/iiif/2/MMNAT01_AF_NNM001001033_001",
  "protocol": "http://iiif.io/api/image",
  "width": 2674,
  "height": 2155,
  "sizes": [
    {
      "width": 84,
      "height": 67
    },
    {
      "width": 167,
      "height": 135
    },
    {
      "width": 334,
      "height": 269
    },
    {
      "width": 669,
      "height": 539
    },
    {
      "width": 1337,
      "height": 1078
    },
    {
      "width": 2674,
      "height": 2155
    }
  ],
  "tiles": [
    {
      "width": 512,
      "height": 512,
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32
      ]
    }
  ],
  "profile": [
    "http://iiif.io/api/image/2/level2.json",
    {
      "formats": [
        "jpg",
        "tif",
        "gif",
        "png"
      ],
      "maxArea": 5762470,
      "qualities": [
        "bitonal",
        "default",
        "gray",
        "color"
      ],
      "supports": [
        "regionByPx",
        "sizeByW",
        "sizeByWhListed",
        "cors",
        "regionSquare",
        "sizeByDistortedWh",
        "canonicalLinkHeader",
        "sizeByConfinedWh",
        "sizeByPct",
        "jsonldMediaType",
        "regionByPct",
        "rotationArbitrary",
        "sizeByH",
        "baseUriRedirect",
        "rotationBy90s",
        "profileLinkHeader",
        "sizeByForcedWh",
        "sizeByWh",
        "mirroring"
      ]
    }
  ]
}
```

**Comment by adolski** [comment]
Hi @arnikz,

The first thing to do would be to enable the delegate script in `cantaloupe.properties`:

`delegate_script.enabled = true`

And then implement `extra_iiif2_information_response_keys()` in your `delegates.rb`. It might look something like:

```ruby
def extra_iiif2_information_response_keys(options = {})
  {
    'dcterms:source' =>  "https://myexamplearchive.org/images/#{context['identifier']}"
  }
end
```
More about this technique here: https://cantaloupe-project.github.io/manual/4.1/endpoints.html#IIIFImageAPI2

**Comment by arnikz** [comment]
Thanks a lot! I'll try it out.

**Comment by arnikz** [comment]
It works fine! One more thing would be to replace the _hard-coded URL_ in `delegates.rb` with the param(s) in the `cantaloupe.properties` config:

`HttpSource.BasicLookupStrategy.url_prefix = https://myexamplearchive.org/images/`
`HttpSource.BasicLookupStrategy.url_suffix = .jpg`

How can I access these?

**Comment by adolski** [comment]
I can think of a couple of ways. One is by accessing the configuration from Ruby over the JRuby-Java bridge:

#### delegates.rb

```ruby
require 'java'
java_import "edu.illinois.library.cantaloupe.config.Configuation"

def extra_iiif2_information_response_keys(options = {})
  config = Configuration.getInstance
  {
    'dcterms:source' => [config.getString("HttpSource.BasicLookupStrategy.url_prefix"),
                         context['identifier'],
                         config.getString("HttpSource.BasicLookupStrategy.url_suffix")].join('/')
  }
end
```

Note that accessing internal Cantaloupe API from the delegate script is officially not supported, but this is unlikely to break anytime soon.

----

Another is by switching to HttpSource's ScriptLookupStrategy:

#### cantaloupe.properties

```
HttpSource.lookup_strategy = ScriptLookupStrategy
```

#### delegates.rb

```ruby
MY_SOURCE_PREFIX = 'https://myexamplearchive.org/images/'
MY_SOURCE_SUFFIX = '.jpg'

def httpsource_resource_info(options = {})
  { 'uri' => source_image_url }
end

def extra_iiif2_information_response_keys(options = {})
  { 'dcterms:source' => source_image_url }
end

def source_image_url
  [MY_SOURCE_PREFIX, context['identifier'], MY_SOURCE_SUFFIX].join('/')
end
```

**Comment by arnikz** [comment]
Thanks for suggestions. However, I have an issue with the first approach:

```
$ mvn clean compile exec:java -Dcantaloupe.config=cantaloupe.properties
...
16:46:47.085 [qtp108824509-19] INFO  e.i.l.c.s.DelegateProxy - Loading script code
NameError: cannot load Java class edu.illinois.library.cantaloupe.config.Configuation
         for_name at org/jruby/javasupport/JavaClass.java:292
         for_name at org/jruby/javasupport/JavaClass.java:288
  get_proxy_class at org/jruby/javasupport/JavaUtilities.java:39
      java_import at uri:classloader:/jruby/java/core_ext/object.rb:44
              map at org/jruby/RubyArray.java:2577
      java_import at uri:classloader:/jruby/java/core_ext/object.rb:37
           <main> at <script>:15
16:46:47.094 [qtp108824509-19] ERROR e.i.l.c.s.DelegateProxyService - org.jruby.embed.EvalFailedException: (NameError) cannot load Java class edu.illinois.library.cantaloupe.config.Configuation
NameError: uninitialized constant CustomDelegate
  const_missing at org/jruby/RubyModule.java:3762
         <main> at <script>:2
16:46:47.112 [qtp108824509-19] ERROR e.i.l.c.s.DelegateProxy - org.jruby.embed.EvalFailedException: (NameError) uninitialized constant CustomDelegate
javax.script.ScriptException: org.jruby.embed.EvalFailedException: (NameError) uninitialized constant CustomDelegate
	at org.jruby.embed.jsr223.JRubyEngine.wrapException(JRubyEngine.java:104)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:93)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:142)
	at edu.illinois.library.cantaloupe.script.DelegateProxy.instantiateDelegate(DelegateProxy.java:145)
	at edu.illinois.library.cantaloupe.script.DelegateProxy.<init>(DelegateProxy.java:138)
	at edu.illinois.library.cantaloupe.script.DelegateProxyService.newDelegateProxy(DelegateProxyService.java:149)
	at edu.illinois.library.cantaloupe.resource.AbstractResource.getDelegateProxy(AbstractResource.java:336)
	at edu.illinois.library.cantaloupe.resource.AbstractResource.authorize(AbstractResource.java:258)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGET(InformationResource.java:63)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1391)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.embed.EvalFailedException: (NameError) uninitialized constant CustomDelegate
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
	... 39 common frames omitted
Caused by: org.jruby.exceptions.NameError: (NameError) uninitialized constant CustomDelegate
	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3762)
	at RUBY.<main>(<script>:2)
...
```

**Comment by adolski** [comment]
Sorry, I made a typo in the `java_import` line. Try the updated version.

**Comment by arnikz** [comment]
Thanks, it worked!
