### ISSUE TITLE
Thrown java.io.IOException while fetching an image via HttpSource

### ISSUE THREAD

**Issue by arnikz** [cantaloupe-project/cantaloupe#400]
While requesting an image stored remotely (TIFF->JPG), I noticed the following lines in the console (related to #398):

```
$ mvn clean compile exec:java -Dcantaloupe.config=cantaloupe.properties
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< edu.illinois.library.cantaloupe:cantaloupe >-------------
[INFO] Building Cantaloupe 4.1.6
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ cantaloupe ---
[INFO] Deleting /home/arni/Downloads/cantaloupe/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cantaloupe ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ cantaloupe ---
[INFO] Compiling 488 source files to /home/arni/Downloads/cantaloupe/target/classes
[INFO] /home/arni/Downloads/cantaloupe/src/main/java/edu/illinois/library/cantaloupe/http/Client.java: Some input files use or override a deprecated API.
[INFO] /home/arni/Downloads/cantaloupe/src/main/java/edu/illinois/library/cantaloupe/http/Client.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ cantaloupe ---
Loading config file: /home/arni/Downloads/cantaloupe/cantaloupe.properties
14:58:13.742 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  e.i.l.c.ApplicationContextListener - Oracle Corporation OpenJDK 64-Bit Server VM 1.8.0_222 / mixed mode
14:58:13.746 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  e.i.l.c.ApplicationContextListener - Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
14:58:13.746 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  e.i.l.c.ApplicationContextListener - Java library path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
14:58:13.747 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  e.i.l.c.ApplicationContextListener - 4 available processor cores
14:58:13.747 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  e.i.l.c.ApplicationContextListener - Heap total: 615MB; max: 3545MB
14:58:13.747 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  e.i.l.c.ApplicationContextListener - Effective temp directory: /tmp
14:58:13.748 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] WARN  e.i.l.c.ApplicationContextListener - The effective temp directory is the system temp directory. Severe errors may result if the application is left running for a long time. Consider setting `temp_pathname` for long-running servers.
14:58:13.749 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  e.i.l.c.ApplicationContextListener - 🍈 Starting Cantaloupe Unknown
14:58:13.761 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  e.i.l.c.s.HeapInvocationCache - Invocation cache limit: 1815040
14:58:14.076 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  e.i.l.c.s.DelegateProxy - Loading script code
14:58:16.454 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O readers for Format.BMP: com.sun.imageio.plugins.bmp.BMPImageReader, com.sun.media.imageioimpl.plugins.bmp.BMPImageReader
14:58:16.455 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O readers for Format.DICOM: 
14:58:16.456 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O readers for Format.GIF: com.sun.imageio.plugins.gif.GIFImageReader
14:58:16.460 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O readers for Format.JPEG2000: com.sun.media.imageioimpl.plugins.jpeg2000.J2KImageReader
14:58:16.465 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O readers for Format.JPEG: com.sun.imageio.plugins.jpeg.JPEGImageReader
14:58:16.465 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O readers for Format.PDF: 
14:58:16.470 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O readers for Format.PNG: com.sun.imageio.plugins.png.PNGImageReader
14:58:16.571 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O readers for Format.TIFF: com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader, it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader
14:58:16.572 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O readers for Format.WebP: 
14:58:16.578 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O writers for Format.GIF: com.sun.imageio.plugins.gif.GIFImageWriter, com.sun.media.imageioimpl.plugins.gif.GIFImageWriter
14:58:16.582 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O writers for Format.JPEG2000: com.sun.media.imageioimpl.plugins.jpeg2000.J2KImageWriter
14:58:16.584 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O writers for Format.JPEG: com.sun.imageio.plugins.jpeg.JPEGImageWriter
14:58:16.584 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O writers for Format.PDF: 
14:58:16.585 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O writers for Format.PNG: com.sun.imageio.plugins.png.PNGImageWriter
14:58:16.601 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O writers for Format.TIFF: it.geosolutions.imageioimpl.plugins.tiff.TIFFImageWriter, com.sun.media.imageioimpl.plugins.tiff.TIFFImageWriter
14:58:16.602 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] DEBUG e.i.l.c.p.c.IIOProviderContextListener - Image I/O writers for Format.WebP: 
14:58:16.622 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  o.e.j.s.h.ContextHandler - Started o.e.j.w.WebAppContext@8c10e2a{Cantaloupe,/,file:///home/arni/Downloads/cantaloupe/src/main/webapp/,AVAILABLE}{src/main/webapp}
14:58:16.659 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  o.e.j.s.AbstractConnector - Started ServerConnector@3466fa57{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8182}
14:58:16.659 [edu.illinois.library.cantaloupe.StandaloneEntry.main()] INFO  o.e.j.s.Server - Started @14166ms
14:58:34.411 [qtp877779126-19] DEBUG e.i.l.c.i.Identifier - Raw path component: 900c341c1c10fff7%2Ffiles%2FMMNAT01_PM_NNM001001033_001 -> decoded: 900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001 -> scale constraint stripped: 900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001 -> slashes substituted: 900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001
14:58:34.412 [qtp877779126-19] INFO  e.i.l.c.r.i.v.ImageResource - Handling GET /iiif/2/900c341c1c10fff7%2Ffiles%2FMMNAT01_PM_NNM001001033_001/full/max/0/default.jpg
14:58:34.413 [qtp877779126-19] DEBUG e.i.l.c.r.i.v.ImageResource - Request headers: Cache-Control: max-age=0; Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9; Upgrade-Insecure-Requests: 1; Connection: keep-alive; User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 OPR/67.0.3575.137; Sec-Fetch-Dest: document; Sec-Fetch-Site: cross-site; Host: localhost:8182; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.9; Sec-Fetch-Mode: navigate
14:58:34.428 [qtp877779126-19] INFO  e.i.l.c.c.InfoCache - Max InfoCache capacity: 2478135 (10% max heap / 150-byte expected average info size)
14:58:34.521 [qtp877779126-19] DEBUG e.i.l.c.s.DelegateProxy - Instantiated delegate object in 89 msec
14:58:34.526 [qtp877779126-19] DEBUG e.i.l.c.c.CacheFactory - getSourceCache(): implementation changed; creating a new instance
14:58:34.721 [qtp877779126-19] DEBUG e.i.l.c.s.HttpSource - Requesting HEAD https://trng-repository.surfsara.nl/deposit/900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001.tif (extra headers: (none))
14:58:35.762 [qtp877779126-19] DEBUG e.i.l.c.p.ProcessorFactory - Java2dProcessor selected for format TIF (AutomaticSelectionStrategy offered Java2dProcessor, GraphicsMagickProcessor, ImageMagickProcessor)
14:58:35.764 [qtp877779126-19] DEBUG e.i.l.c.s.HttpSource - Resolved 900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001 to https://trng-repository.surfsara.nl/deposit/900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001.tif
14:58:35.766 [qtp877779126-19] DEBUG e.i.l.c.p.ProcessorConnector - StreamSource -> StreamProcessor connection between HttpSource and Java2dProcessor
14:58:35.772 [qtp877779126-19] DEBUG e.i.l.c.s.HttpSource - newSeekableStream(): using 524288-byte chunks
14:58:35.780 [qtp877779126-19] DEBUG e.i.l.c.p.c.TIFFImageReader - Using it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader
14:58:35.781 [qtp877779126-19] DEBUG e.i.l.c.p.c.TIFFImageReader - Ignoring metadata? true
14:58:37.033 [qtp877779126-19] DEBUG e.i.l.c.c.InfoService - readInfo(): read 900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001 from Java2dProcessor in 1267 msec
14:58:37.041 [work-nm-3953579] DEBUG e.i.l.c.c.InfoService - putInObjectCache(): adding info: 900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001 (new size: 1)
14:58:37.042 [work-nm-3953579] DEBUG e.i.l.c.c.InfoCache - putInObjectCache(): adding info: 900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001 (new size: 1)
14:58:37.051 [qtp877779126-19] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): authorize() returned true for args: (none) in 2 msec
14:58:37.057 [qtp877779126-19] DEBUG e.i.l.c.r.i.v.ImageResource - Base URI assembled from X-Forwarded headers: http://localhost:8182
14:58:37.059 [qtp877779126-19] DEBUG e.i.l.c.r.ImageRepresentation - Derivative cache not available; writing directly to the response
14:58:37.064 [qtp877779126-19] DEBUG e.i.l.c.p.c.TIFFImageReader - Acquiring region 0,0/2674x2155 from 2674x2155 mono-tiled/mono-striped image
14:59:16.028 [qtp877779126-19] DEBUG e.i.l.c.s.s.HTTPImageInputStream - Downloaded 12 chunks (5779320 (33.38%) of 17313656 bytes); read 99.35% of chunk data; 1 cache hits; 13 cache misses
14:59:16.030 [qtp877779126-19] DEBUG e.i.l.c.s.s.HTTPImageInputStream - Downloaded 12 chunks (5779320 (33.38%) of 17313656 bytes); read 99.35% of chunk data; 1 cache hits; 13 cache misses
14:59:16.031 [qtp877779126-19] DEBUG e.i.l.c.p.c.TIFFImageReader - dispose(): failed to close the input stream: closed
java.io.IOException: closed
	at javax.imageio.stream.ImageInputStreamImpl.checkClosed(ImageInputStreamImpl.java:110)
	at javax.imageio.stream.ImageInputStreamImpl.close(ImageInputStreamImpl.java:857)
	at edu.illinois.library.cantaloupe.source.stream.HTTPImageInputStream.close(HTTPImageInputStream.java:167)
	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.dispose(AbstractIIOImageReader.java:121)
	at edu.illinois.library.cantaloupe.processor.AbstractImageIOProcessor.close(AbstractImageIOProcessor.java:55)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:218)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1391)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
14:59:16.034 [qtp877779126-19] INFO  e.i.l.c.r.ErrorResource - Handling GET /iiif/2/900c341c1c10fff7%2Ffiles%2FMMNAT01_PM_NNM001001033_001/full/max/0/default.jpg
14:59:16.034 [qtp877779126-19] DEBUG e.i.l.c.r.ErrorResource - Request headers: Cache-Control: max-age=0; Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9; Upgrade-Insecure-Requests: 1; Connection: keep-alive; User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 OPR/67.0.3575.137; Sec-Fetch-Dest: document; Sec-Fetch-Site: cross-site; Host: localhost:8182; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.9; Sec-Fetch-Mode: navigate
14:59:16.036 [qtp877779126-19] DEBUG e.i.l.c.r.ErrorResource - Base URI assembled from X-Forwarded headers: http://localhost:8182
14:59:16.151 [qtp877779126-19] DEBUG e.i.l.c.r.HandlerServlet - Responded to GET /iiif/2/900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001/full/max/0/default.jpg with HTTP 500 in 41760 msec
```

**Comment by adolski** [comment]
Thanks for reporting this, @arnikz , it is now fixed on the `release/4.1` branch for inclusion in 4.1.7.
