### ISSUE TITLE
Multi-resolution BigTif Error: width*height > Integer.MAX_VALUE!

### ISSUE THREAD

**Issue by albayenes** [cantaloupe-project/cantaloupe#401]
Hi,

I want to display my tiff image with the following request

    http://localhost:8182/iiif/2/test_002.tif/full/full/0/default.jpg

which has the following structure

`{"@context":"http://iiif.io/api/image/2/context.json","@id":"http://localhost:8182/iiif/2/test_002.tif","protocol":"http://iiif.io/api/image","width":97792,"height":221184,"sizes":[{"width":96,"height":216},{"width":191,"height":432},{"width":382,"height":864},{"width":764,"height":1728},{"width":1528,"height":3456},{"width":3056,"height":6912},{"width":6112,"height":13824},{"width":12224,"height":27648},{"width":24448,"height":55296},{"width":48896,"height":110592},{"width":97792,"height":221184}],"tiles":[{"width":512,"height":512,"scaleFactors":[1,2,4,8,16,32,64,128,256,512,1024]},{"width":512,"height":1024,"scaleFactors":[1,2,4,8,16,32,64,128,256,512,1024]},{"width":3629,"height":1577,"scaleFactors":[1,2,4,8,16,32,64,128,256,512,1024]}],"profile":["http://iiif.io/api/image/2/level2.json",{"formats":["jpg","tif","gif","png"],"qualities":["bitonal","default","gray","color"],"supports":["regionByPx","sizeByW","sizeByWhListed","cors","regionSquare","sizeByDistortedWh","canonicalLinkHeader","sizeByConfinedWh","sizeByPct","jsonldMediaType","regionByPct","rotationArbitrary","sizeByH","baseUriRedirect","rotationBy90s","profileLinkHeader","sizeByForcedWh","sizeByWh","mirroring"]}]}`

It gives the following error. How can I solve the issue?

```
java.lang.IllegalArgumentException: width*height > Integer.MAX_VALUE!
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.getDestination(TIFFImageReader.java:2123)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1727)
	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.tileAwareRead(AbstractIIOImageReader.java:516)
	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.readSmallestUsableSubimage(AbstractIIOImageReader.java:409)
	at edu.illinois.library.cantaloupe.processor.codec.TIFFImageReader.read(TIFFImageReader.java:160)
	at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:64)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.process(ImageRepresentation.java:180)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:147)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:76)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:213)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1391)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by adolski** [comment]
Hi @albayenes,

This error is caused by a limit on the maximum pixel count of a BufferedImage (which is `Integer.MAX_VALUE` or 2^31-1). You are requesting a 97792x221184 derivative image, which is larger than that.

Also, the output format you are requesting (JPEG) is limited to 65,535 pixels on a side.

So try adjusting that URL to select a limited region or smaller scale according to the Image API: 

* https://iiif.io/api/image/2.1/#region
* https://iiif.io/api/image/2.1/#size
