### ISSUE TITLE
How to rewrite URL query string

### ISSUE THREAD

**Issue by arnikz** [cantaloupe-project/cantaloupe#407]
I'd like to access some images in an archive via a collection ID + image ID.

```
# cantaloupe.properties
HttpSource.BasicLookupStrategy.url_prefix = https://trng-repository.surfsara.nl/deposit/
HttpSource.BasicLookupStrategy.url_suffix = .tif
```
For example, requesting a JPG version of [this](https://trng-repository.surfsara.nl/deposit/900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001.tif) TIF image is done via

`http://localhost:8182/iiif/2/900c341c1c10fff7%2Ffiles%2FMMNAT01_PM_NNM001001033_001/full/max/0/default.jpg`

- collection ID = `900c341c1c10fff7`
- image ID = `MMNAT01_PM_NNM001001033_001`

How to configure Cantaloupe to simply request

`http://localhost:8182/iiif/2/900c341c1c10fff7:MMNAT01_PM_NNM001001033_001/full/max/0/default.jpg` (i.e., replacing the encoded `/files/` with `:` in the URL path)?

Thanks!

**Comment by adolski** [comment]
Hi @arnikz,

You will need to set `HttpSource.lookup_strategy = ScriptLookupStrategy` and implement the `httpsource_resource_info()` method in delegates.rb. It might look something like:

```ruby
def httpsource_resource_info(options = {})
  context['identifier'].gsub(':', '/files/')
end
```

**Comment by arnikz** [comment]
Thanks @adolski for swift reply. However, I'm getting the following page

```
500 Internal Server Error`

Invalid URI host: null (authority: null)

java.lang.IllegalArgumentException: Invalid URI host: null (authority: null)
	at org.eclipse.jetty.client.HttpClient.checkHost(HttpClient.java:510)
	at org.eclipse.jetty.client.HttpClient.newHttpRequest(HttpClient.java:495)
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:453)
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:442)
	at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:475)
	at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:458)
	at edu.illinois.library.cantaloupe.source.HttpSource.fetchHEADResponseInfo(HttpSource.java:433)
	at edu.illinois.library.cantaloupe.source.HttpSource.checkAccess(HttpSource.java:259)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:135)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1391)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

and log in the terminal

```
...
melon      | 20:17:49.764 [qtp968514068-18] INFO  e.i.l.c.r.ErrorResource - Handling GET /iiif/2/900c341c1c10fff7:MMNAT01_PM_NNM001001033_001/full/max/0/default.jpg
melon      | 20:17:49.765 [qtp968514068-18] DEBUG e.i.l.c.r.ErrorResource - Request headers: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8; Upgrade-Insecure-Requests: 1; User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0; Connection: keep-alive; Host: localhost:8182; Accept-Language: en-US,en;q=0.5; Accept-Encoding: gzip, deflate; DNT: 1
melon      | 20:17:49.768 [qtp968514068-18] DEBUG e.i.l.c.r.ErrorResource - Base URI assembled from X-Forwarded headers: http://localhost:8182
melon      | 20:17:49.914 [qtp968514068-18] DEBUG e.i.l.c.r.HandlerServlet - Responded to GET /iiif/2/900c341c1c10fff7:MMNAT01_PM_NNM001001033_001/full/max/0/default.jpg with HTTP 500 in 580 msec
```

```bash
$ grep -i httpsource cantaloupe.properties
...
HttpSource.lookup_strategy = ScriptLookupStrategy
HttpSource.BasicLookupStrategy.url_prefix = https://trng-repository.surfsara.nl/deposit/
HttpSource.BasicLookupStrategy.url_suffix = .tif
...

**Comment by adolski** [comment]
Sorry @arnikz, it's Monday:

```ruby
def httpsource_resource_info(options = {})
  'https://trng-repository.surfsara.nl/deposit/' + context['identifier'].gsub(':', '/files/') + '.tif'
end
```

**Comment by arnikz** [comment]
Perfect. Thanks!
