### ISSUE TITLE
Jetty does not accept a null key store password

### ISSUE THREAD

**Issue by rafaeluriarte** [cantaloupe-project/cantaloupe#411]
I am trying to set up Cantaloupe with https and a certificate but I am getting this error:

```
2020-11-02 10:50:57.734:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@1e34c607{Cantaloupe,/,file:///tmp/jetty-0_0_0_0-443-cantaloupe-4_1_6_war-_-any-12932262041489141228.dir/webapp/,AVAILABLE}{/home/XXXXXX/cantaloupe/cantaloupe-4.1.6/cantaloupe-4.1.6.war}
Exception in thread "main" java.lang.NullPointerException
        at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1234)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:374)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:92)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:320)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at edu.illinois.library.cantaloupe.ApplicationServer.start(ApplicationServer.java:350)
        at edu.illinois.library.cantaloupe.StandaloneEntry.main(StandaloneEntry.java:97)

```

The versions are:
OpenJDK 64-Bit Server VM (build 11.0.9+11-post-Debian-1deb10u1, mixed mode, sharing)
cantaloupe-4.1.6 

Here is the config:

```
# !! Configures the HTTP server. (Standalone mode only.)
http.enabled = false
http.host = 0.0.0.0
http.port = 80
http.http2.enabled = false

# !! Configures the HTTPS server. (Standalone mode only.)
https.enabled = true
https.host = 0.0.0.0
https.port = 443
# Secure HTTP/2 requires Java 9 or later.
https.http2.enabled = false
# !! Available values are `JKS` and `PKCS12`. (Standalone mode only.)^M
https.key_store_type = PKCS12
https.key_store_password =
https.key_store_path = /etc/ssl/cert.p12
https.key_password = 
```

Am I doing something wrong?

Thank you very much

**Comment by adolski** [comment]
Hi @rafaeluriarte,

I can reproduce this using a key store with no password set. But if I set a password, it works.

Maybe related: https://github.com/eclipse/jetty.project/issues/1368

It's not obvious to me how to fix this, so setting a password on the key store is what I would recommend in the meantime.

**Comment by rafaeluriarte** [comment]
perfect, it works if a set a password on the key store. Thank you very much

**Comment by cmhdave** [comment]
I've been testing Cantaloupe with the latest version of Jetty (11.0.2) locally and it seems to work ok.  I can open a PR for the work I did on the upgrade, it was all relatively straight-forward.  I did have to upgrade javax.servlet to jakarta.servlet to get it to work but again, very straight-forward.
