### ISSUE TITLE
CMYK JPEG not supported in pyramidal TIFF tiles

### ISSUE THREAD

**Issue by barryspearce** [cantaloupe-project/cantaloupe#414]
I have a PTIF which is generated by VIPS. Standard options all seems good and Gwenview reads OK. GIMP imports TIFF as multiple layers without error. However, Cataloupe refuses to serve the image.

Image was created from source jpg using vips 8.10.1-1

vips tiffsave in.jpg  out.tif --compression jpeg -Q 90 --pyramid --tile --tile-width 256 --tile-height 256

I cannot attach the original jpeg which is 13.5Mb nor the resultant ptif which is 40.3Mb.

The jpeg failing was obtained from:
https://sothebys-md.brightspotcdn.com/62/f8/f93ffdd24065918ce99645c4db20/l18411-9fs2s-1.jpg

Cantaloupe 4.1.4
Java: OpenJDK 64-Bit Server VM 14.0.2 / mixed mode

Stack trace:

500 Internal Server Error

Unsupported Image Type

java.io.IOException: Unsupported Image Type
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:148)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:76)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:213)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: edu.illinois.library.cantaloupe.processor.ProcessorException: Unsupported Image Type
	at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:70)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.process(ImageRepresentation.java:179)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:146)
	... 36 more
Caused by: javax.imageio.IIOException: Unsupported Image Type
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1139)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1110)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFJPEGDecompressor.decodeRaw(TIFFJPEGDecompressor.java:278)
	at it.geosolutions.imageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2627)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1708)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:2009)
	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.tileAwareRead(AbstractIIOImageReader.java:506)
	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.readSmallestUsableSubimage(AbstractIIOImageReader.java:446)
	at edu.illinois.library.cantaloupe.processor.codec.TIFFImageReader.read(TIFFImageReader.java:160)
	at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:64)
	... 38 more

**Comment by adolski** [comment]
Unfortunately the Oracle JPEG reader doesn't support images with CMYK color. There is a hack to get them to work as standalone images, but it won't work when they are embedded inside TIFFs.

Possible workarounds, for the time being, include converting to RGB or using a different compression like LZW or deflate.

**Comment by barryspearce** [comment]
OK. Thanks for the heads up.
I've added a pre-processing of the image if I detect it is on CMYK colorspace. Then I process it using:

vips icc_transform in out.jpg sRGB --intent perceptual

Note: There is a bug in VIPS in 8.10.1 where if the output filename starts ./ it outputs the image data to stdout. I have logged this issue with vips.

Is it possible to use the Twelve Monkeys library instead? Would that make a difference?

**Comment by adolski** [comment]
I'm not familiar with the TwelveMonkeys plugins, but assuming that there is one that can decode CMYK JPEGs, another problem is that the GeoSolutions TIFF reader would need to be modified to select it fpr JPEG decoding: https://github.com/geosolutions-it/imageio-ext/blob/master/plugin/tiff/src/main/java/it/geosolutions/imageioimpl/plugins/tiff/TIFFJPEGDecompressor.java#L171-L180

**Comment by glenrobson** [comment]
Test with latest Cantaloupe to see if its still broken.
