### ISSUE TITLE
Turbojpg has problems showing some jpgs

### ISSUE THREAD

**Issue by erikradisch** [cantaloupe-project/cantaloupe#421]
I have troubles with some jpgs showing it with turbo jpg

cantaloupe throughs the following error:
`java.io.IOException: org.libjpegturbo.turbojpeg.TJException: Corrupt JPEG data: 4116770 extraneous bytes before marker 0xd9
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:159)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:76)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:213)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1391)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: edu.illinois.library.cantaloupe.processor.ProcessorException: org.libjpegturbo.turbojpeg.TJException: Corrupt JPEG data: 4116770 extraneous bytes before marker 0xd9
	at edu.illinois.library.cantaloupe.processor.TurboJpegProcessor.process(TurboJpegProcessor.java:269)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.process(ImageRepresentation.java:190)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:157)
	... 39 more
Caused by: org.libjpegturbo.turbojpeg.TJException: Corrupt JPEG data: 4116770 extraneous bytes before marker 0xd9
	at org.libjpegturbo.turbojpeg.TJDecompressor.decompress(Native Method)
	at org.libjpegturbo.turbojpeg.TJDecompressor.decompress(TJDecompressor.java:803)
	at org.libjpegturbo.turbojpeg.TJDecompressor.decompress(TJDecompressor.java:853)
	at edu.illinois.library.cantaloupe.processor.codec.turbojpeg.TurboJPEGImageReader.readAsBufferedImage(TurboJPEGImageReader.java:574)
	at edu.illinois.library.cantaloupe.processor.TurboJpegProcessor.process(TurboJpegProcessor.java:217)
	... 41 more`

as far as I understood turbojpg, this is only a warning, the jpg would habve been processed, but I am not shure. 
The picture can be found here:
https://cloud.saw-leipzig.de/s/tXGHSk6MXJESRDM

Is this a known issue? Are there any workarounds?

Sincerely,

Erik

**Comment by adolski** [comment]
Thanks for reporting this, @erikradisch. TurboJpegProcessor was using TurboJPEG API that caused an exception to be thrown when encountering a corrupt image. This is now fixed on the `release/4.1` branch for inclusion in 4.1.8.
