### ISSUE TITLE
Null Pointer exception when metadata orientation is enabled for certain JPEG images 4.1.7

### ISSUE THREAD

**Issue by DiegoPino** [cantaloupe-project/cantaloupe#424]
Hi, since 4.1.7 we are getting this `NullPointerException` when asking for a `info.json` for certain images:
and is related to orientation reading: (Java2D processor)

Here is an example:

![Affected Image](https://esie.space/do/102/iiif/506ff0ee-de07-4f06-9772-e730d58c5f09/full/full/0/pano%20parking%20lot_0.jpg)

The dimensions are 8000x4000 pixeles and this image is quite rich in Metadata/XMP/Exif.
If download the image, save back in my computer and reupload error is gone.
All this images had no issue before we enabled "respect orientation" and disabled Preserve metadata because of #409. But in 4.1.7 enven preserve metadata + respect orientation at the same time are leading to the same 500 error.

A request for its info.json leads to this

```
500 Internal Server Error


java.lang.NullPointerException
	at com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata.mergeStandardTree(TIFFImageMetadata.java:1098)
	at com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata.mergeTree(TIFFImageMetadata.java:1630)
	at java.desktop/javax.imageio.metadata.IIOMetadata.setFromTree(IIOMetadata.java:752)
	at com.sun.media.imageio.plugins.tiff.TIFFDirectory.createFromMetadata(TIFFDirectory.java:224)
	at edu.illinois.library.cantaloupe.processor.codec.Util.readOrientation(Util.java:145)
	at edu.illinois.library.cantaloupe.processor.codec.JPEGMetadata.getExifOrientation(JPEGMetadata.java:64)
	at edu.illinois.library.cantaloupe.processor.codec.JPEGMetadata.getOrientation(JPEGMetadata.java:97)
	at edu.illinois.library.cantaloupe.processor.AbstractImageIOProcessor.getEffectiveOrientation(AbstractImageIOProcessor.java:109)
	at edu.illinois.library.cantaloupe.processor.AbstractImageIOProcessor.readInfo(AbstractImageIOProcessor.java:79)
```

## Attaching some of the extracted metadata here (the shared image is a direct link so can be downloaded to get the same metadata)

```JSON
{
 "flv:exif": {
                "Model": "Pixel 3a",
                "FileSize": "4.8 MB",
                "MIMEType": "image\/jpeg",
                "ImageSize": "8000x4000",
                "ImageWidth": 8000,
                "XMPToolkit": "XMP Core 5.5.0",
                "GPSAltitude": "153.5 m Above Sea Level",
                "GPSDateTime": "2020:06:08 22:24:19Z",
                "GPSLatitude": "42 deg 58' 41.66\" N",
                "GPSPosition": "42 deg 58' 41.66\" N, 78 deg 52' 7.45\" W",
                "ImageHeight": 4000,
                "GPSDateStamp": "2020:06:08",
                "GPSLongitude": "78 deg 52' 7.45\" W",
                "GPSTimeStamp": "22:24:19",
                "GPSVersionID": "2.2.0.0",
                "IsPhotosphere": true,
                "LastPhotoDate": "2020:06:08 22:32:02+00:00",
                "SpecialTypeID": "com.google.android.apps.camera.gallery.specialtype.SpecialType-PHOTOSPHERE",
                "FirstPhotoDate": "2020:06:08 22:30:32+00:00",
                "GPSAltitudeRef": "Above Sea Level",
                "GPSLatitudeRef": "North",
                "ProjectionType": "equirectangular",
                "GPSLongitudeRef": "West",
                "DateTimeOriginal": "2020:06:08 18:32:38",
                "SourcePhotosCount": 38,
                "UsePanoramaViewer": true,
                "PoseHeadingDegrees": 174,
                "FullPanoWidthPixels": 8000,
                "GPSProcessingMethod": "fused",
                "CroppedAreaTopPixels": 0,
                "FullPanoHeightPixels": 4000,
                "CroppedAreaLeftPixels": 0,
                "CroppedAreaImageWidthPixels": 8000,
                "LargestValidInteriorRectTop": 0,
                "CroppedAreaImageHeightPixels": 4000,
                "LargestValidInteriorRectLeft": 0,
                "LargestValidInteriorRectWidth": 8704,
                "LargestValidInteriorRectHeight": 4352
            },
            "sequence": 2,
            "flv:pronom": {
                "label": "JPEG File Interchange Format",
                "mimetype": "image\/jpeg",
                "pronom_id": "info:pronom\/fmt\/43",
                "detection_type": "signature"
            },
            "dr:mimetype": "image\/jpeg",
            "crypHashFunc": "md5",
            "flv:identify": {
                "1": {
                    "width": "8000",
                    "format": "JPEG",
                    "height": "4000",
                    "orientation": "Undefined"
                }
            }
  }
}
```

Thanks a lot, any pointers (hopefully not a NULL one!) would be very appreciated.

**Comment by adolski** [comment]
Hi @DiegoPino,

This image has an illegal EXIF orientation value of `0`. `com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata.mergeStandardTree()` does not accept that value, so I added a catch block to swallow the exception it throws and treat unrecognized values as `1` (normal orientation).

**Comment by DiegoPino** [comment]
@adolski thanks a lot, this is great. Hope 2021 brings some rest and happiness. Hugs
