### ISSUE TITLE
5.0.1 - exif.Field - java.lang.IllegalArgumentException: Tag argument is null

### ISSUE THREAD

**Issue by bcail** [cantaloupe-project/cantaloupe#489]
I got the following exception on cantaloupe 5.0.1:
`Caused by: java.lang.IllegalArgumentException: Tag argument is null
        at edu.illinois.library.cantaloupe.image.exif.Field.&#60;init&#62;(Field.java:15)
        at edu.illinois.library.cantaloupe.image.exif.Directory.put(Directory.java:218)
        at edu.illinois.library.cantaloupe.image.exif.Directory.fromTIFFDirectory(Directory.java:51)
        at edu.illinois.library.cantaloupe.image.exif.Directory.fromTIFFDirectory(Directory.java:49)
        at edu.illinois.library.cantaloupe.processor.codec.tiff.TIFFMetadata.getEXIF(TIFFMetadata.java:54)`

Would it be possible to log exif exceptions, but continue generating the derivative image?

**Comment by adolski** [comment]
Hi @bcail , could you share the image with which this is happening?

**Comment by bcail** [comment]
sure, sent you an email.

**Comment by adolski** [comment]
Thanks @bcail , this is fixed now and will be included in 5.0.3.

**Comment by bcail** [comment]
Thanks!
