### ISSUE TITLE
Incorrect info serialization

### ISSUE THREAD

**Issue by aindlq** [cantaloupe-project/cantaloupe#494]
In the latest version I get a lot of `500 Internal Server Error` when derivative cache is enabled, looks like it has to do something with EXIF :

```
500 Internal Server Error

Field is missing value
 at [Source: (String)&#34;{&#34;exif&#34;:{&#34;fields&#34;:[{&#34;tag&#34;:271,&#34;dataType&#34;:2,&#34;value&#34;:&#34;Apple&#34;},{&#34;tag&#34;:272,&#34;dataType&#34;:2,&#34;value&#34;:&#34;iPhone 5&#34;},{&#34;tag&#34;:274,&#34;dataType&#34;:3,&#34;value&#34;:3},{&#34;tag&#34;:282,&#34;dataType&#34;:5,&#34;value&#34;:[72,1]},{&#34;tag&#34;:283,&#34;dataType&#34;:5,&#34;value&#34;:[72,1]},{&#34;tag&#34;:296,&#34;dataType&#34;:3,&#34;value&#34;:2},{&#34;tag&#34;:305,&#34;dataType&#34;:2,&#34;value&#34;:&#34;10.3.3&#34;},{&#34;tag&#34;:306,&#34;dataType&#34;:2,&#34;value&#34;:&#34;2017:09:12 14:33:56&#34;},{&#34;tag&#34;:531,&#34;dataType&#34;:3,&#34;value&#34;:1},{&#34;tag&#34;:34665,&#34;dataType&#34;:9,&#34;value&#34;:{&#34;parentTag&#34;:34665,&#34;fields&#34;:[{&#34;tag&#34;:33434,&#34;dataType&#34;:5,&#34;value&#34;:[1,20]},{&#34;tag&#34;:33&#34;[truncated 2364 chars]; line: 1, column: 2864] (through reference chain: edu.illinois.library.cantaloupe.image.Metadata[&#34;exif&#34;])


com.fasterxml.jackson.databind.JsonMappingException: Field is missing value
 at [Source: (String)&#34;{&#34;exif&#34;:{&#34;fields&#34;:[{&#34;tag&#34;:271,&#34;dataType&#34;:2,&#34;value&#34;:&#34;Apple&#34;},{&#34;tag&#34;:272,&#34;dataType&#34;:2,&#34;value&#34;:&#34;iPhone 5&#34;},{&#34;tag&#34;:274,&#34;dataType&#34;:3,&#34;value&#34;:3},{&#34;tag&#34;:282,&#34;dataType&#34;:5,&#34;value&#34;:[72,1]},{&#34;tag&#34;:283,&#34;dataType&#34;:5,&#34;value&#34;:[72,1]},{&#34;tag&#34;:296,&#34;dataType&#34;:3,&#34;value&#34;:2},{&#34;tag&#34;:305,&#34;dataType&#34;:2,&#34;value&#34;:&#34;10.3.3&#34;},{&#34;tag&#34;:306,&#34;dataType&#34;:2,&#34;value&#34;:&#34;2017:09:12 14:33:56&#34;},{&#34;tag&#34;:531,&#34;dataType&#34;:3,&#34;value&#34;:1},{&#34;tag&#34;:34665,&#34;dataType&#34;:9,&#34;value&#34;:{&#34;parentTag&#34;:34665,&#34;fields&#34;:[{&#34;tag&#34;:33434,&#34;dataType&#34;:5,&#34;value&#34;:[1,20]},{&#34;tag&#34;:33&#34;[truncated 2364 chars]; line: 1, column: 2864] (through reference chain: edu.illinois.library.cantaloupe.image.Metadata[&#34;exif&#34;])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
	at edu.illinois.library.cantaloupe.image.InfoDeserializer.deserialize(InfoDeserializer.java:80)
	at edu.illinois.library.cantaloupe.image.InfoDeserializer.deserialize(InfoDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3299)
	at edu.illinois.library.cantaloupe.image.Info.fromJSON(Info.java:248)
	at edu.illinois.library.cantaloupe.cache.FilesystemCache.getInfo(FilesystemCache.java:536)
	at edu.illinois.library.cantaloupe.cache.InfoService.getInfo(InfoService.java:82)
	at edu.illinois.library.cantaloupe.cache.CacheFacade.getInfo(CacheFacade.java:55)
	at edu.illinois.library.cantaloupe.resource.ImageRequestHandler.handle(ImageRequestHandler.java:300)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:121)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.core.JsonParseException: Field is missing value
 at [Source: (String)&#34;{&#34;exif&#34;:{&#34;fields&#34;:[{&#34;tag&#34;:271,&#34;dataType&#34;:2,&#34;value&#34;:&#34;Apple&#34;},{&#34;tag&#34;:272,&#34;dataType&#34;:2,&#34;value&#34;:&#34;iPhone 5&#34;},{&#34;tag&#34;:274,&#34;dataType&#34;:3,&#34;value&#34;:3},{&#34;tag&#34;:282,&#34;dataType&#34;:5,&#34;value&#34;:[72,1]},{&#34;tag&#34;:283,&#34;dataType&#34;:5,&#34;value&#34;:[72,1]},{&#34;tag&#34;:296,&#34;dataType&#34;:3,&#34;value&#34;:2},{&#34;tag&#34;:305,&#34;dataType&#34;:2,&#34;value&#34;:&#34;10.3.3&#34;},{&#34;tag&#34;:306,&#34;dataType&#34;:2,&#34;value&#34;:&#34;2017:09:12 14:33:56&#34;},{&#34;tag&#34;:531,&#34;dataType&#34;:3,&#34;value&#34;:1},{&#34;tag&#34;:34665,&#34;dataType&#34;:9,&#34;value&#34;:{&#34;parentTag&#34;:34665,&#34;fields&#34;:[{&#34;tag&#34;:33434,&#34;dataType&#34;:5,&#34;value&#34;:[1,20]},{&#34;tag&#34;:33&#34;[truncated 2364 chars]; line: 1, column: 2864]
	at edu.illinois.library.cantaloupe.image.exif.DirectoryDeserializer.deserialize(DirectoryDeserializer.java:104)
	at edu.illinois.library.cantaloupe.image.exif.DirectoryDeserializer.deserialize(DirectoryDeserializer.java:109)
	at edu.illinois.library.cantaloupe.image.exif.DirectoryDeserializer.deserialize(DirectoryDeserializer.java:19)
	at edu.illinois.library.cantaloupe.image.exif.DirectoryDeserializer.deserialize(DirectoryDeserializer.java:13)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	... 44 more
```

I've tried 5.0.2 and also the latest build for 5.0 branch and it makes no difference. 
The problem that this error is quite random. If I drop the cache, it is not always reproducable with the same image. Any ideas what can be the problem?

**Comment by adolski** [comment]
It looks like there are two problems here: one is that apparently a corrupt info is being saved to the cache, and the other is that the deserialization does not fail gracefully. The commit above ought to fix the latter problem, but I still don't know what's causing the former problem. Could you share an image or a cached info that is involved in this?

**Comment by doldman** [comment]
Hi - I just wondered what the current status of this issue is? thanks.

**Comment by adolski** [comment]
The above commit (incorporated into 5.0.3 which was just released) logs info deserialization errors (caused by incorrect serializations) at warning level. If you see any of these warnings, please send me either the info that is causing it (e.g. retrieved from cache), or the related image, and I will try to fix the serialization. (Unfortunately, the JSON in the stack trace is truncated.)
