### ISSUE TITLE
slow memory leak?

### ISSUE THREAD

**Issue by bcail** [cantaloupe-project/cantaloupe#533]
We got an error yesterday:
`    2021-09-06 15:14:42,015 ERROR [qtp361571968-133083] e.i.l.c.r.ImageRepresentation [ImageRepresentation.java:146] write(): Java heap space 
    java.lang.OutOfMemoryError: Java heap space 
        at java.desktop/java.awt.image.PixelInterleavedSampleModel.createSubsetSampleModel(PixelInterleavedSampleModel.java:158)
        at java.desktop/sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1249)
        at java.desktop/sun.awt.image.ByteInterleavedRaster.createChild(ByteInterleavedRaster.java:1203)
        at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageWriter.grabPixels(JPEGImageWriter.java:1680)
        at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
        at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1007)
        at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:371)
        at edu.illinois.library.cantaloupe.processor.codec.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:186)
        at edu.illinois.library.cantaloupe.processor.codec.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:153)
        at edu.illinois.library.cantaloupe.processor.codec.ImageWriterFacade.write(ImageWriterFacade.java:49)
        at edu.illinois.library.cantaloupe.processor.OpenJpegProcessor.processInUnix(OpenJpegProcessor.java:592)
        at edu.illinois.library.cantaloupe.processor.OpenJpegProcessor.process(OpenJpegProcessor.java:482)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.process(ImageRepresentation.java:205)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.copyOrProcess(ImageRepresentation.java:167)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:130)
        at edu.illinois.library.cantaloupe.resource.ImageRequestHandler.handle(ImageRequestHandler.java:405)
        at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:128)
        at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
        at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
`

Cantaloupe had been running since 2021-07-22. We got a similar exception on 2021-06-24, but we've only gotten those heap space exceptions those two days, nothing in between.

We're using a jruby delegate for finding the image file for cantaloupe to process. Is there something I need to watch out for in my delegate code? Could there be a memory leak in jruby?

Thanks.

**Comment by adolski** [comment]
There is not a lot of information to go on here. What is the heap size, how much load, what are the characteristics of the source and derivative images, does the application recover or does it need to be restarted, etc. This stack trace suggests that the exception is happening while writing a JPEG, so you might try searching the logs shortly before this event to find the request (by matching the thread ID). Alternatively, maybe there was a flurry of requests around this time and the GC was not able to kick in fast enough.

Without knowing more, I would suspect transient load spikes. I would not suspect JRuby involvement unless you are using tons of memory in your delegate script for some reason.

**Comment by bcail** [comment]
The delegate script isn't large - it does some splitting and hashing of the ID, to find the directory where the file is.

I did run the Eclipse Memory Analyzer, and it had two suspected leaks - do either of these look like valid issues?
![leak suspect 1a](https://user-images.githubusercontent.com/2394596/132539070-554638b7-a2f8-4fd7-8993-f07f9939e341.png)
![leak suspect 1b](https://user-images.githubusercontent.com/2394596/132539094-5e05be07-b5f8-4d6f-8fb1-931f2bbc2594.png)
![leak suspect 2](https://user-images.githubusercontent.com/2394596/132539117-4ceb5bcc-2c8e-43c6-bde3-396f99ab9176.png)

**Comment by adolski** [comment]
I haven't used that tool before, but I don't see anything particularly interesting there. Where it says "5,742,320 (22.40%) bytes"--is this implying that the whole heap is 5742320 / 0.224 = ~25MB? This might be the case when it has just started up. In that case it would be better to look at a heap dump taken at the time of the OutOfMemoryError. But even if you were to do that, I bet all you'd find is a bunch of `byte[]`s and other stuff belonging to all of the BufferedImages that are filling up the heap.

I don't suspect a memory leak. If an app is running and getting pounded on for weeks or months, I would expect it to fail sooner and not recover.

**Comment by bcail** [comment]
I did use that tool on my laptop, when cantaloupe was just started up and hadn't processed much.

I got more OutOfMemory issues today. Maybe I'll look at increasing the jvm memory parameters.
