### ISSUE TITLE
Strange response

### ISSUE THREAD

**Issue by wezy01** [cantaloupe-project/cantaloupe#544]
Hello,

I'm using Cantaloupe 5.0.5 and I want to implement IIIF authentication.
For that I'm using a delegates.rb file.
I want to return a 401 in some cases.

Here is my (cleaned) delegates.rb file

require 'java'
require 'uri'
require 'net/http'

class CustomDelegate
  attr_accessor :context

  def pre_authorize(options = {})
       logger = Java::edu.illinois.library.cantaloupe.delegate.Logger

	path = 'http://10.2.0.22/test.php'

	ident = context['identifier']

	uri = URI(path + '?file=' + ident)
	res = Net::HTTP.get(uri)

	if res == '1'
	    true
        else
		return {
        		'status_code' => 401,
        		'challenge' => 'Bearer charset="UTF-8"'
    		}
	end
  end

  def authorize(options = {})
    true
  end

end

So if res isn't "1" it's unauthorized and returns a 401.
From my understandings the info.json must contain a json with the information but in my case I'm getting the following in info.json

401 Unauthorized

Unauthorized

edu.illinois.library.cantaloupe.resource.ResourceException: Unauthorized
	at edu.illinois.library.cantaloupe.resource.AbstractResource.processAuthInfo(AbstractResource.java:368)
	at edu.illinois.library.cantaloupe.resource.AbstractResource.preAuthorize(AbstractResource.java:334)
	at edu.illinois.library.cantaloupe.resource.iiif.v3.InformationResource.access$000(InformationResource.java:25)
	at edu.illinois.library.cantaloupe.resource.iiif.v3.InformationResource$1CustomCallback.authorize(InformationResource.java:63)
	at edu.illinois.library.cantaloupe.resource.InformationRequestHandler.handle(InformationRequestHandler.java:209)
	at edu.illinois.library.cantaloupe.resource.iiif.v3.InformationResource.doGET(InformationResource.java:85)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:831)

This results in a popup error in Mirador
In Chrome and edge it says : SyntaxError: Unexpected token U in JSON at position 4
In Firefox : SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 5 of the JSON data

Any idea what could be going wrong here?

**Comment by adolski** [comment]
Try moving your auth logic out of `pre_authorize()` and into `authorize()`.
