### ISSUE TITLE
HttpSource.BasicLookupStrategy.url_prefix not used at all in 5.0.5?

### ISSUE THREAD

**Issue by hrvoj3e** [cantaloupe-project/cantaloupe#570]
`url_prefix` is not prepended to identifier
 - can't figure out why!?

```
root@server2 /s/s/c/d/server1# ag httpsource setting 
140:# `HttpSource`, `JdbcSource`, `S3Source`, and `AzureStorageSource`.
142:source.static = HttpSource
166:# HttpSource
170:HttpSource.allow_insecure = false
174:HttpSource.request_timeout =
176:# Tells HttpSource how to look up resources. Allowed values are
179:HttpSource.lookup_strategy = BasicLookupStrategy
184:HttpSource.BasicLookupStrategy.url_prefix = https://my.example.net/pb/
188:HttpSource.BasicLookupStrategy.url_suffix =
191:HttpSource.BasicLookupStrategy.auth.basic.username =
192:HttpSource.BasicLookupStrategy.auth.basic.secret =
196:#HttpSource.chunking.enabled = true
197:HttpSource.chunking.enabled = false
200:HttpSource.chunking.chunk_size = 512K
204:HttpSource.chunking.cache.enabled = true
207:HttpSource.chunking.cache.max_size = 5M
```

```
/usr/bin/java -Dcantaloupe.config=/srv/services/cantaloupe/deploy/server1/setting -Xms6g -Xmx12g -jar /srv/services/cantaloupe/5.0.x/5.0.5.jar
```

`https://my-iiif.example.net/iiif/2/edb6zs2a%2Fpart%2Fg%2F11%2Fmvu%2Fg11mvub98p8p.jpg/0,0,2000,1430/1000,/0/default.jpg?cache=nocache`

 - it makes no sense to get `Expected URL scheme 'http' or 'https' but no colon was found` when I have defined URL prefix which has `https`

```
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1332)
	at okhttp3.HttpUrl.get(HttpUrl.java:917)
	at okhttp3.Request$Builder.url(Request.java:165)
	at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:449)
	at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:567)
	at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:555)
	at edu.illinois.library.cantaloupe.source.HttpSource.fetchHEADResponseInfo(HttpSource.java:530)
	at edu.illinois.library.cantaloupe.source.HttpSource.checkAccess(HttpSource.java:481)
	at edu.illinois.library.cantaloupe.resource.ImageRequestHandler.handle(ImageRequestHandler.java:338)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:128)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

```
Mar 17 07:34:18 server2 java[15695]: 07:34:18.861 [qtp1438098656-65] INFO  e.i.l.c.r.i.v.ImageResource - Handling GET /iiif/2/edb6zs2a%2Fpart%2Fg%2F11%2Fmvu%2Fg11mvub98p8p.jpg/0,0,2000,1430/1000,/0/default.jpg
Mar 17 07:34:18 server2 java[15695]: 07:34:18.862 [qtp1438098656-65] DEBUG e.i.l.c.r.i.v.ImageResource - Request headers: sec-fetch-mode: navigate; Cookie: _ga=GA1.2.1160440256.1606742468; sec-fetch-site: none; Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9; X-Forwarded-Proto: https; X-Forwarded-Host: my-iiif.example.net; Connection: close; User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.136 Safari/537.36; Host: 127.0.0.1:7051; Accept-Encoding: gzip, deflate, br; sec-fetch-user: ?1; X-Forwarded-Port: 443; X-Forwarded-Path: /; sec-ch-ua: "Chromium";v="98", " Not A;Brand";v="99"; sec-ch-ua-mobile: ?0; Cache-Control: max-age=0; sec-ch-ua-platform: "Linux"; upgrade-insecure-requests: 1; X-Forwarded-For: 217.xxx.211.xxx; Accept-Language: en-US,en;q=0.9,hr;q=0.8; sec-fetch-dest: document
Mar 17 07:34:18 server2 java[15695]: 07:34:18.864 [qtp1438098656-65] DEBUG e.i.l.c.i.MetaIdentifier - [Raw path component: edb6zs2a%2Fpart%2Fg%2F11%2Fmvu%2Fg11mvub98p8p.jpg] -> [decoded: edb6zs2a/part/g/11/mvu/g11mvub98p8p.jpg] -> [slashes substituted: edb6zs2a/part/g/11/mvu/g11mvub98p8p.jpg]
Mar 17 07:34:18 server2 java[15695]: 07:34:18.865 [qtp1438098656-65] DEBUG e.i.l.c.i.Identifier - [Raw path component: edb6zs2a%2Fpart%2Fg%2F11%2Fmvu%2Fg11mvub98p8p.jpg] -> [decoded: edb6zs2a/part/g/11/mvu/g11mvub98p8p.jpg] -> [slashes substituted: edb6zs2a/part/g/11/mvu/g11mvub98p8p.jpg]
Mar 17 07:34:18 server2 java[15695]: 07:34:18.868 [qtp1438098656-65] DEBUG e.i.l.c.c.FilesystemCache - getSourceImageFile(): /srv/services/cantaloupe/deploy/server1/cache/source/0c/dd/94/0cdd9429bc63baf6b6fe26c69d167417
Mar 17 07:34:18 server2 java[15695]: 07:34:18.869 [qtp1438098656-65] INFO  e.i.l.c.r.ErrorResource - Handling GET /iiif/2/edb6zs2a%2Fpart%2Fg%2F11%2Fmvu%2Fg11mvub98p8p.jpg/0,0,2000,1430/1000,/0/default.jpg
Mar 17 07:34:18 server2 java[15695]: 07:34:18.869 [qtp1438098656-65] DEBUG e.i.l.c.r.ErrorResource - Request headers: sec-fetch-mode: navigate; Cookie: _ga=GA1.2.1160440256.1606742468; sec-fetch-site: none; Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9; X-Forwarded-Proto: https; X-Forwarded-Host: my-iiif.example.net; Connection: close; User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.136 Safari/537.36; Host: 127.0.0.1:7051; Accept-Encoding: gzip, deflate, br; sec-fetch-user: ?1; X-Forwarded-Port: 443; X-Forwarded-Path: /; sec-ch-ua: "Chromium";v="98", " Not A;Brand";v="99"; sec-ch-ua-mobile: ?0; Cache-Control: max-age=0; sec-ch-ua-platform: "Linux"; upgrade-insecure-requests: 1; X-Forwarded-For: 217.xxx.211.xxx; Accept-Language: en-US,en;q=0.9,hr;q=0.8; sec-fetch-dest: document
Mar 17 07:34:18 server2 java[15695]: 07:34:18.870 [qtp1438098656-65] DEBUG e.i.l.c.r.ErrorResource - Base URI assembled from X-Forwarded headers: https://my-iiif.example.net
Mar 17 07:34:18 server2 java[15695]: 07:34:18.874 [qtp1438098656-65] DEBUG e.i.l.c.r.HandlerServlet - Responded to GET /iiif/2/edb6zs2a/part/g/11/mvu/g11mvub98p8p.jpg/0,0,2000,1430/1000,/0/default.jpg with HTTP 500 in 14 msec
```

**Comment by adolski** [comment]
This is pretty baffling. Your configuration and usage look right to me.

If you could post the actual value of your `HttpSource.BasicLookupStrategy.url_prefix`, or send it to me privately, I could try it on my end. I can't reproduce the problem when I use a different https host.

**Comment by hrvoj3e** [comment]
[@adolski](https://github.com/adolski) You have mail.

**Comment by adolski** [comment]
Both of the examples you sent me do work on my end.

The behavior you are seeing would be consistent with a blank `HttpSource.BasicLookupStrategy.url_prefix` value. I wonder if you have multiple config files and are launching Cantaloupe with the wrong one?

Do the log messages from HttpSource look correct? E.g.

```
DEBUG e.i.l.c.s.HttpSource - Resolved edb6zs2a/part/g/11/mvu/g11mvub98p8p.jpg to ...
```

If you unzip a fresh Cantaloupe and run it locally, on your desktop, changing only the `source.static` and `HttpSource.BasicLookupStrategy.url_prefix` keys, does it work there?

**Comment by hrvoj3e** [comment]
I tried locally - works. Problem was in systemd service which sets ENV variables and there was empty url_prefix.
Ah...tunnel vision. Thank you for the hint.

Anyway. How can I debug / dump current config values?
Is there an admin endpoint which will show:
 - which config was loaded
 - which values are populated
 - from where are they populated (file, env)

**Comment by adolski** [comment]
Glad you got it working.

There is an API endpoint to retrieve the current config values: https://cantaloupe-project.github.io/manual/5.0/endpoints.html#retrieve-configuration

There is no way to find out where the config values originate from, but the config file location is logged at startup.
