### ISSUE TITLE
overlay not seeing context?

### ISSUE THREAD

**Issue by PietroLiuzzo** [cantaloupe-project/cantaloupe#589]
Hi!

I  have some trouble with the `overlay()` function. I am running cantaloupe 5.0.5.

cantaloupe.properties is set as from the docs.
in my delegates.rb this is after def filesystemsource_pathname() and pre-authorize() I have copied and lightly modified two examples from the docs. if the image is cropped in a viewer, should not get overlay and equally if requested at a size less of 320.

```
 def overlay(options = {})
   resulting_size = context['resulting_size']
   if context['operations'].find{ |op| op['class'].include?('Crop') }
   return nil
   elsif resulting_size['width'] < 320 or
        resulting_size['height'] < 320
   return nil
   else
   {
      'image' => 'smalllogo.png',
      'position' => 'top left',
      'inset' => 10
    }
    end
  end

```
The overlay does not show. 

application.log has
```
2022-05-12 15:55:03,141 TRACE [qtp1546908073-12] e.i.l.c.o.o.OverlayFactory [OverlayFactory.java:62] Using a DelegateOverlayService
2022-05-12 15:55:03,141 TRACE [qtp1546908073-12] e.i.l.c.d.JRubyDelegateProxy [JRubyDelegateProxy.java:383] invokeUncached(): invoking overlay() with args: (none)
2022-05-12 15:55:03,155 ERROR [qtp1546908073-12] e.i.l.c.o.OperationList [OperationList.java:317] java.lang.NoSuchMethodException: (NoMethodError) undefined method `find' for nil:NilClass
javax.script.ScriptException: java.lang.NoSuchMethodException: (NoMethodError) undefined method `find' for nil:NilClass
        at edu.illinois.library.cantaloupe.delegate.JRubyDelegateProxy.invoke(JRubyDelegateProxy.java:397)
        at edu.illinois.library.cantaloupe.delegate.JRubyDelegateProxy.invoke(JRubyDelegateProxy.java:364)
        at edu.illinois.library.cantaloupe.delegate.JRubyDelegateProxy.getOverlayProperties(JRubyDelegateProxy.java:289)
        at edu.illinois.library.cantaloupe.operation.overlay.DelegateOverlayService.overlayProperties(DelegateOverlayService.java:139)
        at edu.illinois.library.cantaloupe.operation.overlay.DelegateOverlayService.newOverlay(DelegateOverlayService.java:41)
        at edu.illinois.library.cantaloupe.operation.overlay.OverlayFactory.newOverlay(OverlayFactory.java:85)
        at edu.illinois.library.cantaloupe.operation.OperationList.applyNonEndpointMutations(OperationList.java:313)
        at edu.illinois.library.cantaloupe.resource.ImageRequestHandler.handle(ImageRequestHandler.java:387)
        at edu.illinois.library.cantaloupe.resource.iiif.v3.ImageResource.doGET(ImageResource.java:130)
        at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
        at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
```

which makes me think that context is not passed perhaps? or does not yet know about resulting_size? 
What have I done wrong?

thanks a lot!

**Comment by adolski** [comment]
Thanks for reporting this, @PietroLiuzzo, it appears to be a simple bug that the above commit (on the `release/5.0` branch) should fix. The fix will be included in the 5.0.6 release, but I don't know when that will be.

**Comment by PietroLiuzzo** [comment]
Thanks a lot! do you think I can replicate the change?

**Comment by adolski** [comment]
Do you mean use it before it's released? Sure, just do something like:

```
git clone https://github.com/cantaloupe-project/cantaloupe.git
cd cantaloupe
git checkout release/5.0
mvn clean package -DskipTests
```

This will produce `target/cantaloupe-5.0.x.jar` which you can swap in in place of your current one.

**Comment by PietroLiuzzo** [comment]
That worked well. Thanks a lot!
