### ISSUE TITLE
Getting EOFException with TurboJpegProcessor

### ISSUE THREAD

**Issue by erikradisch** [cantaloupe-project/cantaloupe#590]
Using TurboJpegProcessor, 
I do get the following error retrieving a jpeg:
```
500 Internal Server Error



java.io.EOFException
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readShort(ImageInputStreamImpl.java:229)
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readUnsignedShort(ImageInputStreamImpl.java:242)
	at edu.illinois.library.cantaloupe.image.exif.Reader.read(Reader.java:113)
	at edu.illinois.library.cantaloupe.image.exif.Reader.read(Reader.java:129)
	at edu.illinois.library.cantaloupe.image.exif.Reader.read(Reader.java:97)
	at edu.illinois.library.cantaloupe.processor.TurboJpegProcessor.readMetadata(TurboJpegProcessor.java:275)
	at edu.illinois.library.cantaloupe.processor.TurboJpegProcessor.readInfo(TurboJpegProcessor.java:263)
	at edu.illinois.library.cantaloupe.cache.InfoService.readInfo(InfoService.java:220)
	at edu.illinois.library.cantaloupe.cache.InfoService.getOrReadInfo(InfoService.java:153)
	at edu.illinois.library.cantaloupe.cache.CacheFacade.getOrReadInfo(CacheFacade.java:67)
	at edu.illinois.library.cantaloupe.resource.AbstractRequestHandler.getOrReadInfo(AbstractRequestHandler.java:39)
	at edu.illinois.library.cantaloupe.resource.InformationRequestHandler.handle(InformationRequestHandler.java:287)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGET(InformationResource.java:85)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

For reproduction, you can call:
https://iiif.saw-leipzig.de/iiif/2/kucha%2Fimages%2F3517.jpg/0,0,2048,2048/2048,/0/default.jpg

Is this a known issue? Or do I do something wrong?

**Comment by adolski** [comment]
This looks like a bug. Could you post the source image somewhere where I can access it?

**Comment by erikradisch** [comment]
Sure, you find it here:
https://cloud.saw-leipzig.de/s/q85pxSFzfFfBkrn

**Comment by adolski** [comment]
Thanks @erikradisch , I'm busy with other things right now but I will look into this when I can.

**Comment by erikradisch** [comment]
hey @adolski any updates on that? do you have an Idea, what is causing the trouble? Maybe I could try and help?

**Comment by glenrobson** [comment]
Test and see if its an issue.

**Comment by vljukap98** [comment]
We just had this occurring on this image: https://digitalizirani.hismus.hr/h15mu533/main/r/m8/a6t/rm8a6t115j19.jpg
The issue most likely is a faulty EXIF:

```shell
exiftool rm8a6t115j19.jpg
Warning                         : Bad offset for IFD0 StripOffsets
```

Or with using `-v` flag, there are multiple warnings reported:

```shell
exiftool -v rm8a6t115j19.jpg
JPEG APP1 (2046 bytes):
  ExifByteOrder = II
  + [IFD0 directory with 14 entries]
  | 0)  ImageWidth = 7956
  | 1)  ImageHeight = 11126
  | 2)  BitsPerSample = 8 8 8
  | 3)  Compression = 1
  | 4)  PhotometricInterpretation = 2
  | Warning = Bad offset for IFD0 StripOffsets
  | 5)  StripOffsets
  | 6)  SamplesPerPixel = 3
  | 7)  RowsPerStrip = 16
  | Warning = Bad offset for IFD0 StripByteCounts
  | 8)  StripByteCounts
  | Warning = Bad offset for IFD0 XResolution
  | 9)  XResolution
  | Warning = Bad offset for IFD0 YResolution
  | 10) YResolution
  | 11) PlanarConfiguration = 1
  | 12) ResolutionUnit = 2
  | Warning = Bad offset for IFD0 ICC_Profile
  | 13) ICC_Profile (SubDirectory) -->
```

One additional note is that my stack trace differs somewhat, but not much:

```
500 Internal Server Error



java.io.EOFException
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:385)
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:396)
	at edu.illinois.library.cantaloupe.image.exif.Reader.readBytes(Reader.java:158)
	at edu.illinois.library.cantaloupe.image.exif.Reader.read(Reader.java:145)
	at edu.illinois.library.cantaloupe.image.exif.Reader.read(Reader.java:97)
	at edu.illinois.library.cantaloupe.processor.TurboJpegProcessor.readMetadata(TurboJpegProcessor.java:376)
	at edu.illinois.library.cantaloupe.processor.TurboJpegProcessor.readInfo(TurboJpegProcessor.java:364)
	at edu.illinois.library.cantaloupe.cache.InfoService.readInfo(InfoService.java:220)
	at edu.illinois.library.cantaloupe.cache.InfoService.getOrReadInfo(InfoService.java:153)
	at edu.illinois.library.cantaloupe.cache.CacheFacade.getOrReadInfo(CacheFacade.java:67)
	at edu.illinois.library.cantaloupe.resource.AbstractRequestHandler.getOrReadInfo(AbstractRequestHandler.java:39)
	at edu.illinois.library.cantaloupe.resource.ImageRequestHandler.handle(ImageRequestHandler.java:392)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:141)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1583)


```

This could or probably is an issue with the image producer, but could it be handled when serving images?
