### ISSUE TITLE
Update to 5.0.6 throws a `Unrecoverable error in HandlerServlet:` Caused by `java.lang.NoClassDefFoundError`

### ISSUE THREAD

**Issue by bbarberBPL** [cantaloupe-project/cantaloupe#642]
Hi there. We just tried updating our cantaloupe staging server and when we tried to access the default route The following stack trace appears on the page.

```
Unrecoverable error in HandlerServlet:

java.lang.NoClassDefFoundError: Could not initialize class edu.illinois.library.cantaloupe.resource.VelocityRepresentation
  at edu.illinois.library.cantaloupe.resource.ErrorResource.doGET(ErrorResource.java:116)
  at edu.illinois.library.cantaloupe.resource.HandlerServlet.handleError(HandlerServlet.java:153)
  at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:118)
  at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  at org.eclipse.jetty.server.Server.handle(Server.java:516)
  at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
  at org.eclipse.jetty.io.ssl.SslConnection$1.run(SslConnection.java:149)
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
  at java.base/java.lang.Thread.run(Thread.java:829)
```
The OS we are using is Ubuntu 18.04 

The java version is 
```
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```

We are also running `canatloupe` in standalone mode via `systemd` service and through a reverve proxy via `nginx`

Here is the command we are using in the `systemd` service
```
[Unit]
...
[Service]
...
ExecStart=/bin/bash -c "java -Dcantaloupe.config=/usr/local/cantaloupe/cantaloupe.properties -Xms2G -Xmx2G -jar /usr/local/cantaloupe/cantaloupe-5.0.5.jar" # This still works
# ExecStart=/bin/bash -c "java -Dcantaloupe.config=/usr/local/cantaloupe/cantaloupe.properties -Xms2G -Xmx2G -jar /usr/local/cantaloupe/cantaloupe-5.0.6.jar" # This rasises error
[Install]
...
```
 I don't think `nginx` is the issue in this case because when I access the ip/port cantaloupe is running on I get the same error as above. I also don't think its our properties file because it works with version `5.0.5`. If you need anything else from us let me know and I will get you that info ASAP. Thank you.

**Comment by glenrobson** [comment]
Hi @bbarberBPL, I've setup a similar setup to run in docker:


```
docker run -it -p 8182:8182 ubuntu:18.04
apt-get update && apt-get -y install openjdk-11-jdk unzip vim curl
 cd /usr/local/src/
 curl -LO https://github.com/cantaloupe-project/cantaloupe/releases/download/v5.0.6/cantaloupe-5.0.6.zip
 unzip cantaloupe-5.0.6.zip 
 cd cantaloupe-5.0.6
 cp cantaloupe.properties.sample cantaloupe.properties
 vim cantaloupe.properties
 java -Dcantaloupe.config=./cantaloupe.properties -Xmx2g -jar cantaloupe-5.0.6.jar
```

and it seems to be working OK for me. Was there a particular webpage or image you were accessing? If so I can try and re-create the issue on my side to find out what is going on. 

Thanks

**Comment by bbarberBPL** [comment]
> Hi @bbarberBPL, I've setup a similar setup to run in docker:
> 
> ```
> docker run -it -p 8182:8182 ubuntu:18.04
> apt-get update && apt-get -y install openjdk-11-jdk unzip vim curl
>  cd /usr/local/src/
>  curl -LO https://github.com/cantaloupe-project/cantaloupe/releases/download/v5.0.6/cantaloupe-5.0.6.zip
>  unzip cantaloupe-5.0.6.zip 
>  cd cantaloupe-5.0.6
>  cp cantaloupe.properties.sample cantaloupe.properties
>  vim cantaloupe.properties
>  java -Dcantaloupe.config=./cantaloupe.properties -Xmx2g -jar cantaloupe-5.0.6.jar
> ```
> 
> and it seems to be working OK for me. Was there a particular webpage or image you were accessing? If so I can try and re-create the issue on my side to find out what is going on.
> 
> Thanks

Hi @glenrobson  I was just accessing the root/home page for the application when it threw that.  I'm also using a different user/group `cantaloupe:cantaloupe` in this case. But I've verified that the permissions for all the files/ folders are exactly the same as the 5.0.5 version folder and that version works.

**Comment by glenrobson** [comment]
Thanks, how did you install the new version? Did you unzip the one on the release page?

**Comment by bbarberBPL** [comment]
> Thanks, how did you install the new version? Did you unzip the one on the release page

Yup. I downloaded it from the release page and unzipped it locally.

**Comment by bbarberBPL** [comment]
@glenrobson I just realized something after looking over your docker example.. We are using the config file from 5.0.5. Were there any config options in the recent release that would have caused breaking changes?

**Comment by glenrobson** [comment]
I don't think there were any changes between 5.0.5 and 5.0.6 with the config file. Maybe it would be worth doing a diff but 5.0.6 was only a library update so there shouldn't be any config changes.

How did you do the upgrade? Is it running on a new machine or is the 5.0.5 version of cantaloupe still on the same machine you are using?

**Comment by glenrobson** [comment]
Hi @bbarberBPL any update? I saw another mention of this issue on the Samvera slack so I'm keen to get to the bottom of it. 

Thanks

Glen

**Comment by bbarberBPL** [comment]
> I don't think there were any changes between 5.0.5 and 5.0.6 with the config file. Maybe it would be worth doing a diff but 5.0.6 was only a library update so there shouldn't be any config changes.
> 
> How did you do the upgrade? Is it running on a new machine or is the 5.0.5 version of cantaloupe still on the same machine you are using?

Its running on the same machine. Sorry for the delayed response. We haven't attempted to do any further debugging. So the issue remains the same as before

**Comment by glenrobson** [comment]
No problem and thanks for getting back. Did you unzip it into the same directory as 5.0.5 or a new directory?

**Comment by DiegoPino** [comment]
re @glenrobson question: Cantaloupe expands/caches libraries (jar files) in its temp folder, so maybe even if not deployed in the same folder, there are chances old jars might be still being loaded. Stop cantaloupe, check where your tmp folder config points to and empty it first and then start it again. Maybe not the issue but who knows

**Comment by bbarberBPL** [comment]
> No problem and thanks for getting back. Did you unzip it into the same directory as 5.0.5 or a new directory?

@glenrobson we unzipped it into a new directory

**Comment by bbarberBPL** [comment]
@glenrobson. I was finally able to diagnose the problem. We had the 
`log.error.FileAppender.enabled = true`  AND `log.error.RollingFileAppender.enabled = true` set in `cantaloupe.properties` Not sure how this worked before with 5.0.5 but after I set `log.error.FileAppender.enabled = false` It stopped throwing this error

**Comment by glenrobson** [comment]
Thanks @bbarberBPL. Thats great news you found a fix and thanks for letting us know the solution.
