### ISSUE TITLE
JAI Processor Tiled-TIFFs: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kaij** [cantaloupe-project/cantaloupe#94]
There seems to be a problem with Tiled TIFFs (JPEG compression, generated with VIPS, tile size 256x256px). The rightmost tile is not displayed correctly at certain resolutions. In the backend, there's the attached exception.

Do you have seen this before? If needed, I can provide more information and a detailed test case. I'm using v3.2.3 (release).

- Update 1: I reproduced it also with TIFFs compressed by ImageMagick.
- Update 2: added starting part of exception

`nbvv-iiif         | java.io.IOException: java.lang.ArrayIndexOutOfBoundsException
nbvv-iiif         | 	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:99)
nbvv-iiif         | 	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
nbvv-iiif         | 	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
nbvv-iiif         | 	at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
nbvv-iiif         | 	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:187)
nbvv-iiif         | 	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
nbvv-iiif         | 	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
nbvv-iiif         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
...
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
nbvv-iiif         | 	at javax.media.jai.PlanarImage.cobbleByte(PlanarImage.java:2902)
nbvv-iiif         | 	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2169)
nbvv-iiif         | 	at javax.media.jai.GeometricOpImage.computeTile(GeometricOpImage.java:678)
nbvv-iiif         | 	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
nbvv-iiif         | 	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
nbvv-iiif         | 	at javax.media.jai.PlanarImage.copyData(PlanarImage.java:2343)
nbvv-iiif         | 	at javax.media.jai.RenderedOp.copyData(RenderedOp.java:2299)
nbvv-iiif         | 	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2525)
nbvv-iiif         | 	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2546)
nbvv-iiif         | 	at edu.illinois.library.cantaloupe.processor.imageio.JpegImageWriter.write(JpegImageWriter.java:169)
nbvv-iiif         | 	at edu.illinois.library.cantaloupe.processor.imageio.ImageWriter.write(ImageWriter.java:90)
nbvv-iiif         | 	at edu.illinois.library.cantaloupe.processor.JaiProcessor.process(JaiProcessor.java:217)
nbvv-iiif         | 	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:138)
nbvv-iiif         | 	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:87)
nbvv-iiif         | 	... 30 common frames omitted`

**Comment by adolski** [comment]
Hi @kaij, thanks for reporting this. Would you be able to post this image somewhere where I can grab it, as well as the URL you are requesting?

**Comment by kaij** [comment]
The images are not yet available publicly, but I have put a temporary copy to one of them here: https://www.dropbox.com/s/a6s56vsqvca97gm/baumann_imagick.tif?dl=0 (200MB). Also attached is an image of how it will look (OpenSeadragon viewer). The image is quite large (29049 × 5329 pixels)

The failing request urls are:
Tile a.Tile failed to load: 
- https://nbvv.dev/iiif/2/baumann_imagick.tif/16384,0,12665,5329/792,/0/default.jpg - error: Image load aborted
- https://nbvv.dev/iiif/2/baumann_imagick.tif/24576,0,4473,5329/560,/0/default.jpg - error: Image load aborted

A non failing request is:
- https://nbvv.dev/iiif/2/baumann_imagick.tif/12288,0,4096,4096/1024,/0/default.jpg

![image](https://cloud.githubusercontent.com/assets/1143418/23277737/463817dc-fa0f-11e6-8250-77d26938b935.png)

**Comment by adolski** [comment]
Thank you, I have it downloaded and I'll try to take a look soon.

**Comment by adolski** [comment]
This is a bug in JAI. I noticed previously that it also affects Deflate-compressed TIFFs, and I had implemented a quick fix for those that involves using a different JAI scale operation with a nearest-neighbor resample filter. Unfortunately this provides poor quality.

For the time being, I've extended this fix to other compressed TIFFs. But, I'd like to leave this issue open and see if I can patch JAI to fix this properly. (JAI is no longer maintained, unfortunately.)

If you don't want to wait for the next release, and are OK with lower-quality downscaled tiles when using compressed TIFFs with JaiProcessor, you can build yourself a custom 3.2 snapshot from a clone using `mvn clean; mvn package -Dmaven.test.skip=true` on the `release/3.2` branch. Another option would be to use Java2dProcessor, which is unaffected.

**Comment by kaij** [comment]
Thanks for the quick analysis! Unfortunately, JAI still seems to have best performance for this kind of jpeg-pyramidal TIFF (with this size), but for the moment I'll try your fix and also check whether Java2D could be an option.

**Comment by glenrobson** [comment]
Seems like this was fixed in 3.0.
